/*
Deployment script for UCosmicTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO


PRINT N'Dropping [People].[Affiliation].[IX_CampusId]...';


GO
DROP INDEX [IX_CampusId]
    ON [People].[Affiliation];


GO
PRINT N'Dropping [People].[Affiliation].[IX_CollegeId]...';


GO
DROP INDEX [IX_CollegeId]
    ON [People].[Affiliation];


GO
PRINT N'Dropping [People].[Affiliation].[IX_DepartmentId]...';


GO
DROP INDEX [IX_DepartmentId]
    ON [People].[Affiliation];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityValues] DROP CONSTRAINT [FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] DROP CONSTRAINT [FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityLocation] DROP CONSTRAINT [FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityTag] DROP CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityType] DROP CONSTRAINT [FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId];


GO
PRINT N'Dropping FK_Employees.Employee_Employees.EmployeeFacultyRank_FacultyRankId...';


GO
ALTER TABLE [Employees].[Employee] DROP CONSTRAINT [FK_Employees.Employee_Employees.EmployeeFacultyRank_FacultyRankId];


GO
PRINT N'Dropping FK_Employees.Employee_People.Person_PersonId...';


GO
ALTER TABLE [Employees].[Employee] DROP CONSTRAINT [FK_Employees.Employee_People.Person_PersonId];


GO
PRINT N'Dropping FK_External.ServiceBoolAttribute_External.ServiceIntegration_TenantId_IntegrationName...';


GO
ALTER TABLE [External].[ServiceBoolAttribute] DROP CONSTRAINT [FK_External.ServiceBoolAttribute_External.ServiceIntegration_TenantId_IntegrationName];


GO
PRINT N'Dropping FK_External.ServiceDateTimeAttribute_External.ServiceIntegration_TenantId_IntegrationName...';


GO
ALTER TABLE [External].[ServiceDateTimeAttribute] DROP CONSTRAINT [FK_External.ServiceDateTimeAttribute_External.ServiceIntegration_TenantId_IntegrationName];


GO
PRINT N'Dropping FK_External.ServiceIntAttribute_External.ServiceIntegration_TenantId_IntegrationName...';


GO
ALTER TABLE [External].[ServiceIntAttribute] DROP CONSTRAINT [FK_External.ServiceIntAttribute_External.ServiceIntegration_TenantId_IntegrationName];


GO
PRINT N'Dropping FK_People.Affiliation_Establishments.Establishment_CampusId...';


GO
ALTER TABLE [People].[Affiliation] DROP CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_CampusId];


GO
PRINT N'Dropping FK_People.Affiliation_Establishments.Establishment_CollegeId...';


GO
ALTER TABLE [People].[Affiliation] DROP CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_CollegeId];


GO
PRINT N'Dropping FK_People.Affiliation_Establishments.Establishment_DepartmentId...';


GO
ALTER TABLE [People].[Affiliation] DROP CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_DepartmentId];


GO
PRINT N'Dropping [Employees].[Employee]...';


GO
DROP TABLE [Employees].[Employee];


GO
PRINT N'Dropping [External].[ServiceBoolAttribute]...';


GO
DROP TABLE [External].[ServiceBoolAttribute];


GO
PRINT N'Dropping [External].[ServiceDateTimeAttribute]...';


GO
DROP TABLE [External].[ServiceDateTimeAttribute];


GO
PRINT N'Dropping [External].[ServiceIntAttribute]...';


GO
DROP TABLE [External].[ServiceIntAttribute];


GO
PRINT N'Dropping [External].[ServiceSync]...';


GO
DROP TABLE [External].[ServiceSync];


GO
PRINT N'Starting rebuilding table [ActivitiesV2].[ActivityValues]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [ActivitiesV2].[tmp_ms_xx_ActivityValues] (
    [RevisionId]          INT              IDENTITY (1, 1) NOT NULL,
    [ActivityId]          INT              NOT NULL,
    [Title]               NVARCHAR (500)   NULL,
    [Content]             NTEXT            NULL,
    [ContentSearchable]   NVARCHAR (MAX)   NULL,
    [StartsOn]            DATETIME         NULL,
    [EndsOn]              DATETIME         NULL,
    [OnGoing]             BIT              NULL,
    [StartsFormat]        VARCHAR (10)     NULL,
    [EndsFormat]          VARCHAR (10)     NULL,
    [Mode]                NVARCHAR (20)    NOT NULL,
    [WasExternallyFunded] BIT              NULL,
    [WasInternallyFunded] BIT              NULL,
    [EntityId]            UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]        DATETIME         NOT NULL,
    [CreatedByPrincipal]  NVARCHAR (256)   NULL,
    [UpdatedOnUtc]        DATETIME         NULL,
    [UpdatedByPrincipal]  NVARCHAR (256)   NULL,
    [Version]             ROWVERSION       NOT NULL,
    [IsCurrent]           BIT              NOT NULL,
    [IsArchived]          BIT              NOT NULL,
    [IsDeleted]           BIT              NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_ActivitiesV2.ActivityValues] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [ActivitiesV2].[ActivityValues])
    BEGIN
        SET IDENTITY_INSERT [ActivitiesV2].[tmp_ms_xx_ActivityValues] ON;
        INSERT INTO [ActivitiesV2].[tmp_ms_xx_ActivityValues] ([RevisionId], [ActivityId], [Title], [Content], [StartsOn], [EndsOn], [OnGoing], [StartsFormat], [EndsFormat], [Mode], [WasExternallyFunded], [WasInternallyFunded], [EntityId], [CreatedOnUtc], [CreatedByPrincipal], [UpdatedOnUtc], [UpdatedByPrincipal], [IsCurrent], [IsArchived], [IsDeleted])
        SELECT   [RevisionId],
                 [ActivityId],
                 [Title],
                 [Content],
                 [StartsOn],
                 [EndsOn],
                 [OnGoing],
                 [StartsFormat],
                 [EndsFormat],
                 [Mode],
                 [WasExternallyFunded],
                 [WasInternallyFunded],
                 [EntityId],
                 [CreatedOnUtc],
                 [CreatedByPrincipal],
                 [UpdatedOnUtc],
                 [UpdatedByPrincipal],
                 [IsCurrent],
                 [IsArchived],
                 [IsDeleted]
        FROM     [ActivitiesV2].[ActivityValues]
        ORDER BY [RevisionId] ASC;
        SET IDENTITY_INSERT [ActivitiesV2].[tmp_ms_xx_ActivityValues] OFF;
    END

DROP TABLE [ActivitiesV2].[ActivityValues];

EXECUTE sp_rename N'[ActivitiesV2].[tmp_ms_xx_ActivityValues]', N'ActivityValues';

EXECUTE sp_rename N'[ActivitiesV2].[tmp_ms_xx_constraint_PK_ActivitiesV2.ActivityValues]', N'PK_ActivitiesV2.ActivityValues', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [ActivitiesV2].[ActivityValues].[IX_ActivityId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ActivityId]
    ON [ActivitiesV2].[ActivityValues]([ActivityId] ASC);


GO
PRINT N'Altering [People].[Affiliation]...';


GO
ALTER TABLE [People].[Affiliation] DROP COLUMN [CampusId], COLUMN [CollegeId], COLUMN [DepartmentId];


GO
PRINT N'Creating FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityValues] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId] FOREIGN KEY ([ActivityId]) REFERENCES [ActivitiesV2].[Activity] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityLocation] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityTag] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityType] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO

ALTER TABLE [ActivitiesV2].[ActivityValues] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId];

ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId];

ALTER TABLE [ActivitiesV2].[ActivityLocation] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId];

ALTER TABLE [ActivitiesV2].[ActivityTag] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId];

ALTER TABLE [ActivitiesV2].[ActivityType] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId];


GO
PRINT N'Update complete.';


GO
