/*
Deployment script for UCosmicTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
PRINT N'Creating [Places].[PlaceComposition]...';


GO
CREATE TABLE [Places].[PlaceComposition] (
    [CompositeId] INT NOT NULL,
    [ComponentId] INT NOT NULL,
    CONSTRAINT [PK_Places.PlaceComposition] PRIMARY KEY CLUSTERED ([CompositeId] ASC, [ComponentId] ASC)
);


GO
PRINT N'Creating [Places].[PlaceComposition].[IX_CompositeId]...';


GO
CREATE NONCLUSTERED INDEX [IX_CompositeId]
    ON [Places].[PlaceComposition]([CompositeId] ASC);


GO
PRINT N'Creating [Places].[PlaceComposition].[IX_ComponentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ComponentId]
    ON [Places].[PlaceComposition]([ComponentId] ASC);


GO
PRINT N'Creating FK_Places.PlaceComposition_Places.Place_CompositeId...';


GO
ALTER TABLE [Places].[PlaceComposition] WITH NOCHECK
    ADD CONSTRAINT [FK_Places.PlaceComposition_Places.Place_CompositeId] FOREIGN KEY ([CompositeId]) REFERENCES [Places].[Place] ([RevisionId]);


GO
PRINT N'Creating FK_Places.PlaceComposition_Places.Place_ComponentId...';


GO
ALTER TABLE [Places].[PlaceComposition] WITH NOCHECK
    ADD CONSTRAINT [FK_Places.PlaceComposition_Places.Place_ComponentId] FOREIGN KEY ([ComponentId]) REFERENCES [Places].[Place] ([RevisionId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
ALTER TABLE [Places].[PlaceComposition] WITH CHECK CHECK CONSTRAINT [FK_Places.PlaceComposition_Places.Place_CompositeId];

ALTER TABLE [Places].[PlaceComposition] WITH CHECK CHECK CONSTRAINT [FK_Places.PlaceComposition_Places.Place_ComponentId];


GO
PRINT N'Update complete.';


GO
