/*
Deployment script for UCosmicTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;




GO
PRINT N'Dropping on [dbo].[EdmMetadata]...';


GO
ALTER TABLE [dbo].[EdmMetadata] DROP CONSTRAINT [PK__EdmMetad__3214EC0738996AB5];


GO
PRINT N'Creating [HomeAlert]...';


GO
CREATE SCHEMA [HomeAlert]
    AUTHORIZATION [dbo];


GO
PRINT N'Creating [HomeAlert].[HomeAlert]...';


GO
CREATE TABLE [HomeAlert].[HomeAlert] (
    [Id]              INT            IDENTITY (1, 1) NOT NULL,
    [EstablishmentId] INT            NULL,
    [Text]            NVARCHAR (MAX) NOT NULL,
    CONSTRAINT [PK_HomeAlert.HomeAlert] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [HomeAlert].[HomeAlert].[IX_EstablishmentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EstablishmentId]
    ON [HomeAlert].[HomeAlert]([EstablishmentId] ASC);


GO
PRINT N'Creating [HomeAlert].[FK_HomeAlert.HomeAlert_Establishments.Establishment_EstablishmentId]...';


GO
ALTER TABLE [HomeAlert].[HomeAlert] WITH NOCHECK
    ADD CONSTRAINT [FK_HomeAlert.HomeAlert_Establishments.Establishment_EstablishmentId] FOREIGN KEY ([EstablishmentId]) REFERENCES [Establishments].[Establishment] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';




GO
ALTER TABLE [HomeAlert].[HomeAlert] WITH CHECK CHECK CONSTRAINT [FK_HomeAlert.HomeAlert_Establishments.Establishment_EstablishmentId];


GO
PRINT N'Update complete.';


GO
