/*
Deployment script for UCosmicTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO

PRINT N'Dropping FK_Employees.EmployeeActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeActivityType] DROP CONSTRAINT [FK_Employees.EmployeeActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityType_Employees.EmployeeActivityType_TypeId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityType] DROP CONSTRAINT [FK_ActivitiesV2.ActivityType_Employees.EmployeeActivityType_TypeId];


GO
PRINT N'Dropping FK_Employees.EmployeeModuleSettings_Establishments.Establishment_EstablishmentId...';


GO
ALTER TABLE [Employees].[EmployeeModuleSettings] DROP CONSTRAINT [FK_Employees.EmployeeModuleSettings_Establishments.Establishment_EstablishmentId];


GO
PRINT N'Dropping FK_Employees.EmployeeFacultyRank_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeFacultyRank] DROP CONSTRAINT [FK_Employees.EmployeeFacultyRank_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];


GO
PRINT N'Dropping FK_Employees.EmployeeModuleSettingsNotifyingAdmins_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeModuleSettingsNotifyingAdmins] DROP CONSTRAINT [FK_Employees.EmployeeModuleSettingsNotifyingAdmins_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];


GO
PRINT N'Starting rebuilding table [Employees].[EmployeeActivityType]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [Employees].[tmp_ms_xx_EmployeeActivityType] (
    [Id]                       INT            IDENTITY (1, 1) NOT NULL,
    [Type]                     NVARCHAR (128) NOT NULL,
    [Rank]                     INT            NOT NULL,
    [CssColor]                 NVARCHAR (MAX) NULL,
    [IconLength]               INT            NULL,
    [IconMimeType]             NVARCHAR (MAX) NULL,
    [IconName]                 NVARCHAR (200) NULL,
    [IconPath]                 NVARCHAR (MAX) NULL,
    [IconFileName]             NVARCHAR (210) NULL,
    [EmployeeModuleSettingsId] INT            NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Employees.EmployeeActivityType] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [Employees].[EmployeeActivityType])
    BEGIN
        SET IDENTITY_INSERT [Employees].[tmp_ms_xx_EmployeeActivityType] ON;
        INSERT INTO [Employees].[tmp_ms_xx_EmployeeActivityType] ([Id], [Type], [Rank], [CssColor], [EmployeeModuleSettingsId])
        SELECT   [Id],
                 [Type],
                 [Rank],
                 [CssColor],
                 [EmployeeModuleSettingsId]
        FROM     [Employees].[EmployeeActivityType]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [Employees].[tmp_ms_xx_EmployeeActivityType] OFF;
    END

DROP TABLE [Employees].[EmployeeActivityType];

EXECUTE sp_rename N'[Employees].[tmp_ms_xx_EmployeeActivityType]', N'EmployeeActivityType';

EXECUTE sp_rename N'[Employees].[tmp_ms_xx_constraint_PK_Employees.EmployeeActivityType]', N'PK_Employees.EmployeeActivityType', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [Employees].[EmployeeActivityType].[IX_EmployeeModuleSettingsId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EmployeeModuleSettingsId]
    ON [Employees].[EmployeeActivityType]([EmployeeModuleSettingsId] ASC);


GO
PRINT N'Starting rebuilding table [Employees].[EmployeeModuleSettings]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [Employees].[tmp_ms_xx_EmployeeModuleSettings] (
    [Id]                         INT            IDENTITY (1, 1) NOT NULL,
    [NotifyAdminOnUpdate]        BIT            NOT NULL,
    [PersonalInfoAnchorText]     NVARCHAR (64)  NULL,
    [OfferCountry]               BIT            NOT NULL,
    [OfferActivityType]          BIT            NOT NULL,
    [OfferFundingQuestions]      BIT            NOT NULL,
    [InternationalPedigreeTitle] NVARCHAR (64)  NULL,
    [ReportsDefaultYearRange]    INT            NULL,
    [GlobalViewIconLength]       INT            NULL,
    [GlobalViewIconMimeType]     NVARCHAR (MAX) NULL,
    [GlobalViewIconName]         NVARCHAR (200) NULL,
    [GlobalViewIconPath]         NVARCHAR (MAX) NULL,
    [GlobalViewIconFileName]     NVARCHAR (210) NULL,
    [FindAnExpertIconLength]     INT            NULL,
    [FindAnExpertIconMimeType]   NVARCHAR (MAX) NULL,
    [FindAnExpertIconName]       NVARCHAR (200) NULL,
    [FindAnExpertIconPath]       NVARCHAR (MAX) NULL,
    [FindAnExpertIconFileName]   NVARCHAR (210) NULL,
    [EstablishmentId]            INT            NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Employees.EmployeeModuleSettings] PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [Employees].[EmployeeModuleSettings])
    BEGIN
        SET IDENTITY_INSERT [Employees].[tmp_ms_xx_EmployeeModuleSettings] ON;
        INSERT INTO [Employees].[tmp_ms_xx_EmployeeModuleSettings] ([Id], [NotifyAdminOnUpdate], [PersonalInfoAnchorText], [OfferCountry], [OfferActivityType], [OfferFundingQuestions], [InternationalPedigreeTitle], [ReportsDefaultYearRange], [EstablishmentId])
        SELECT   [Id],
                 [NotifyAdminOnUpdate],
                 [PersonalInfoAnchorText],
                 [OfferCountry],
                 [OfferActivityType],
                 [OfferFundingQuestions],
                 [InternationalPedigreeTitle],
                 [ReportsDefaultYearRange],
                 [EstablishmentId]
        FROM     [Employees].[EmployeeModuleSettings]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [Employees].[tmp_ms_xx_EmployeeModuleSettings] OFF;
    END

DROP TABLE [Employees].[EmployeeModuleSettings];

EXECUTE sp_rename N'[Employees].[tmp_ms_xx_EmployeeModuleSettings]', N'EmployeeModuleSettings';

EXECUTE sp_rename N'[Employees].[tmp_ms_xx_constraint_PK_Employees.EmployeeModuleSettings]', N'PK_Employees.EmployeeModuleSettings', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [Employees].[EmployeeModuleSettings].[IX_EstablishmentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EstablishmentId]
    ON [Employees].[EmployeeModuleSettings]([EstablishmentId] ASC);


GO
PRINT N'Creating [People].[Affiliation].[IX_CampusId]...';


GO
CREATE NONCLUSTERED INDEX [IX_CampusId]
    ON [People].[Affiliation]([CampusId] ASC);


GO
PRINT N'Creating [People].[Affiliation].[IX_CollegeId]...';


GO
CREATE NONCLUSTERED INDEX [IX_CollegeId]
    ON [People].[Affiliation]([CollegeId] ASC);


GO
PRINT N'Creating [People].[Affiliation].[IX_DepartmentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_DepartmentId]
    ON [People].[Affiliation]([DepartmentId] ASC);


GO
PRINT N'Creating FK_People.Affiliation_Establishments.Establishment_CampusId...';


GO
ALTER TABLE [People].[Affiliation] WITH NOCHECK
    ADD CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_CampusId] FOREIGN KEY ([CampusId]) REFERENCES [Establishments].[Establishment] ([RevisionId]);


GO
PRINT N'Creating FK_People.Affiliation_Establishments.Establishment_CollegeId...';


GO
ALTER TABLE [People].[Affiliation] WITH NOCHECK
    ADD CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_CollegeId] FOREIGN KEY ([CollegeId]) REFERENCES [Establishments].[Establishment] ([RevisionId]);


GO
PRINT N'Creating FK_People.Affiliation_Establishments.Establishment_DepartmentId...';


GO
ALTER TABLE [People].[Affiliation] WITH NOCHECK
    ADD CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_DepartmentId] FOREIGN KEY ([DepartmentId]) REFERENCES [Establishments].[Establishment] ([RevisionId]);


GO
PRINT N'Creating FK_Employees.EmployeeActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeActivityType] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId] FOREIGN KEY ([EmployeeModuleSettingsId]) REFERENCES [Employees].[EmployeeModuleSettings] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_ActivitiesV2.ActivityType_Employees.EmployeeActivityType_TypeId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityType] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityType_Employees.EmployeeActivityType_TypeId] FOREIGN KEY ([TypeId]) REFERENCES [Employees].[EmployeeActivityType] ([Id]);


GO
PRINT N'Creating FK_Employees.EmployeeModuleSettings_Establishments.Establishment_EstablishmentId...';


GO
ALTER TABLE [Employees].[EmployeeModuleSettings] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeModuleSettings_Establishments.Establishment_EstablishmentId] FOREIGN KEY ([EstablishmentId]) REFERENCES [Establishments].[Establishment] ([RevisionId]);


GO
PRINT N'Creating FK_Employees.EmployeeFacultyRank_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeFacultyRank] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeFacultyRank_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId] FOREIGN KEY ([EmployeeModuleSettingsId]) REFERENCES [Employees].[EmployeeModuleSettings] ([Id]);


GO
PRINT N'Creating FK_Employees.EmployeeModuleSettingsNotifyingAdmins_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeModuleSettingsNotifyingAdmins] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeModuleSettingsNotifyingAdmins_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId] FOREIGN KEY ([EmployeeModuleSettingsId]) REFERENCES [Employees].[EmployeeModuleSettings] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
ALTER TABLE [People].[Affiliation] WITH CHECK CHECK CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_CampusId];

ALTER TABLE [People].[Affiliation] WITH CHECK CHECK CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_CollegeId];

ALTER TABLE [People].[Affiliation] WITH CHECK CHECK CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_DepartmentId];

ALTER TABLE [Employees].[EmployeeActivityType] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];

ALTER TABLE [ActivitiesV2].[ActivityType] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityType_Employees.EmployeeActivityType_TypeId];

ALTER TABLE [Employees].[EmployeeModuleSettings] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeModuleSettings_Establishments.Establishment_EstablishmentId];

ALTER TABLE [Employees].[EmployeeFacultyRank] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeFacultyRank_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];

ALTER TABLE [Employees].[EmployeeModuleSettingsNotifyingAdmins] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeModuleSettingsNotifyingAdmins_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];


GO
PRINT N'Update complete.';


GO
