/*
Deployment script for UCosmicTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
--:setvar DatabaseName "UCosmicTest"
--:setvar DefaultFilePrefix "UCosmicTest"
--:setvar DefaultDataPath "c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"
--:setvar DefaultLogPath "c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"

--GO
--:on error exit
--GO
--/*
--Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
--To re-enable the script after enabling SQLCMD mode, execute the following:
--SET NOEXEC OFF; 
--*/
--:setvar __IsSqlCmdEnabled "True"
--GO
--IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
--    BEGIN
--        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
--        SET NOEXEC ON;
--    END


--GO
USE [UCosmicTest];


GO
PRINT N'Dropping FK_Places.GeoPlanetPlace_Places.Place_PlaceId...';


GO
ALTER TABLE [Places].[GeoPlanetPlace] DROP CONSTRAINT [FK_Places.GeoPlanetPlace_Places.Place_PlaceId];


GO
PRINT N'Dropping FK_Places.PlaceName_Places.Place_NameForPlaceId...';


GO
ALTER TABLE [Places].[PlaceName] DROP CONSTRAINT [FK_Places.PlaceName_Places.Place_NameForPlaceId];


GO
PRINT N'Dropping FK_Places.PlaceNode_Places.Place_AncestorId...';


GO
ALTER TABLE [Places].[PlaceNode] DROP CONSTRAINT [FK_Places.PlaceNode_Places.Place_AncestorId];


GO
PRINT N'Dropping FK_Places.PlaceNode_Places.Place_OffspringId...';


GO
ALTER TABLE [Places].[PlaceNode] DROP CONSTRAINT [FK_Places.PlaceNode_Places.Place_OffspringId];


GO
PRINT N'Dropping FK_Places.Place_Places.Place_ParentId...';


GO
ALTER TABLE [Places].[Place] DROP CONSTRAINT [FK_Places.Place_Places.Place_ParentId];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityLocation_Places.Place_PlaceId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityLocation] DROP CONSTRAINT [FK_ActivitiesV2.ActivityLocation_Places.Place_PlaceId];


GO
PRINT N'Dropping FK_Establishments.EstablishmentLocationInPlace_Places.Place_PlaceId...';


GO
ALTER TABLE [Establishments].[EstablishmentLocationInPlace] DROP CONSTRAINT [FK_Establishments.EstablishmentLocationInPlace_Places.Place_PlaceId];


GO
PRINT N'Dropping FK_Places.GeoNamesToponym_Places.Place_PlaceId...';


GO
ALTER TABLE [Places].[GeoNamesToponym] DROP CONSTRAINT [FK_Places.GeoNamesToponym_Places.Place_PlaceId];


GO
PRINT N'Dropping FK_People.Person_Files.LoadableFile_PhotoId...';


GO
ALTER TABLE [People].[Person] DROP CONSTRAINT [FK_People.Person_Files.LoadableFile_PhotoId];


GO
/*
The column [Files].[LoadableFile].[Path] is being dropped, data loss could occur.
*/

--IF EXISTS (select top 1 1 from [Files].[LoadableFile])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
PRINT N'Altering [Files].[LoadableFile]...';


GO
ALTER TABLE [Files].[LoadableFile] DROP COLUMN [Path];


GO
PRINT N'Starting rebuilding table [Places].[Place]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

/*
The column [Places].[Place].[IsRegion] on table [Places].[Place] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.

The column [Places].[Place].[IsWater] on table [Places].[Place] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

--IF EXISTS (select top 1 1 from [Places].[Place])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
CREATE TABLE [Places].[tmp_ms_xx_Place] (
    [RevisionId]         INT              IDENTITY (1, 1) NOT NULL,
    [Latitude]           FLOAT (53)       NULL,
    [Longitude]          FLOAT (53)       NULL,
    [NorthLatitude]      FLOAT (53)       NULL,
    [EastLongitude]      FLOAT (53)       NULL,
    [SouthLatitude]      FLOAT (53)       NULL,
    [WestLongitude]      FLOAT (53)       NULL,
    [OfficialName]       NVARCHAR (200)   NOT NULL,
    [IsEarth]            BIT              NOT NULL,
    [IsContinent]        BIT              NOT NULL,
    [IsCountry]          BIT              NOT NULL,
    [IsWater]            BIT              NOT NULL,
    [IsRegion]           BIT              NOT NULL,
    [IsAdmin1]           BIT              NOT NULL,
    [IsAdmin2]           BIT              NOT NULL,
    [IsAdmin3]           BIT              NOT NULL,
    [EntityId]           UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]       DATETIME         NOT NULL,
    [CreatedByPrincipal] NVARCHAR (256)   NULL,
    [UpdatedOnUtc]       DATETIME         NULL,
    [UpdatedByPrincipal] NVARCHAR (256)   NULL,
    [Version]            ROWVERSION       NOT NULL,
    [IsCurrent]          BIT              NOT NULL,
    [IsArchived]         BIT              NOT NULL,
    [IsDeleted]          BIT              NOT NULL,
    [ParentId]           INT              NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Places.Place] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [Places].[Place])
    BEGIN
        SET IDENTITY_INSERT [Places].[tmp_ms_xx_Place] ON;
        INSERT INTO [Places].[tmp_ms_xx_Place] ([RevisionId], [Latitude], [Longitude], [NorthLatitude], [EastLongitude], [SouthLatitude], [WestLongitude], [OfficialName], [IsEarth], [IsContinent], [IsCountry], [IsWater], [IsRegion], [IsAdmin1], [IsAdmin2], [IsAdmin3], [EntityId], [CreatedOnUtc], [CreatedByPrincipal], [UpdatedOnUtc], [UpdatedByPrincipal], [IsCurrent], [IsArchived], [IsDeleted], [ParentId])
        SELECT   [RevisionId],
                 [Latitude],
                 [Longitude],
                 [NorthLatitude],
                 [EastLongitude],
                 [SouthLatitude],
                 [WestLongitude],
                 [OfficialName],
                 [IsEarth],
                 [IsContinent],
                 [IsCountry],
                 0,
                 0,
                 [IsAdmin1],
                 [IsAdmin2],
                 [IsAdmin3],
                 [EntityId],
                 [CreatedOnUtc],
                 [CreatedByPrincipal],
                 [UpdatedOnUtc],
                 [UpdatedByPrincipal],
                 [IsCurrent],
                 [IsArchived],
                 [IsDeleted],
                 [ParentId]
        FROM     [Places].[Place]
        ORDER BY [RevisionId] ASC;
        SET IDENTITY_INSERT [Places].[tmp_ms_xx_Place] OFF;
    END

DROP TABLE [Places].[Place];

EXECUTE sp_rename N'[Places].[tmp_ms_xx_Place]', N'Place';

EXECUTE sp_rename N'[Places].[tmp_ms_xx_constraint_PK_Places.Place]', N'PK_Places.Place', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [Places].[Place].[IX_ParentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ParentId]
    ON [Places].[Place]([ParentId] ASC);


GO
PRINT N'Creating [Places].[Place].[IX_Place_IsCountry]...';


GO
CREATE NONCLUSTERED INDEX [IX_Place_IsCountry]
    ON [Places].[Place]([IsCountry] ASC);


GO
PRINT N'Creating [Places].[Place].[IX_Place_OfficialName]...';


GO
CREATE NONCLUSTERED INDEX [IX_Place_OfficialName]
    ON [Places].[Place]([OfficialName] ASC);


GO
PRINT N'Creating [Places].[Place].[IX_Place_OfficialName_RevisionId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Place_OfficialName_RevisionId]
    ON [Places].[Place]([OfficialName] ASC, [RevisionId] ASC)
    INCLUDE([Latitude], [Longitude], [NorthLatitude], [EastLongitude], [SouthLatitude], [WestLongitude], [IsEarth], [IsContinent], [IsCountry], [IsAdmin1], [IsAdmin2], [IsAdmin3], [EntityId], [CreatedOnUtc], [CreatedByPrincipal], [UpdatedOnUtc], [UpdatedByPrincipal], [Version], [IsCurrent], [IsArchived], [IsDeleted], [ParentId]);


GO
PRINT N'Creating [Places].[Place].[IX_Place_RevisionId]...';


GO
CREATE NONCLUSTERED INDEX [IX_Place_RevisionId]
    ON [Places].[Place]([RevisionId] ASC)
    INCLUDE([ParentId]);


GO
/*
The column [Representatives].[RepModuleSettings].[EmailAddress] is being dropped, data loss could occur.
*/

--IF EXISTS (select top 1 1 from [Representatives].[RepModuleSettings])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
PRINT N'Altering [Representatives].[RepModuleSettings]...';


GO
ALTER TABLE [Representatives].[RepModuleSettings] DROP COLUMN [EmailAddress];


GO
PRINT N'Creating [Files].[ExternalFile]...';


GO
CREATE TABLE [Files].[ExternalFile] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [Length]   BIGINT         NOT NULL,
    [MimeType] NVARCHAR (256) NOT NULL,
    [Name]     NVARCHAR (MAX) NULL,
    [Path]     NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Files.ExternalFile] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Representatives].[ApplicationRecipient]...';


GO
CREATE TABLE [Representatives].[ApplicationRecipient] (
    [Id]           INT            IDENTITY (1, 1) NOT NULL,
    [OwnerId]      INT            NOT NULL,
    [EmailAddress] NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Representatives.ApplicationRecipient] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Representatives].[ApplicationRecipient].[IX_OwnerId]...';


GO
CREATE NONCLUSTERED INDEX [IX_OwnerId]
    ON [Representatives].[ApplicationRecipient]([OwnerId] ASC);


GO
PRINT N'Creating [Places].[Place].[ST_Place_OfficialName_RevisionId]...';


GO
CREATE STATISTICS [ST_Place_OfficialName_RevisionId]
    ON [Places].[Place]([RevisionId], [OfficialName]);


GO
PRINT N'Creating [Places].[Place].[ST_Place_RevisionId_ParentId_OfficialName_Ises_LatLng_Boxing_EntityId]...';


GO
CREATE STATISTICS [ST_Place_RevisionId_ParentId_OfficialName_Ises_LatLng_Boxing_EntityId]
    ON [Places].[Place]([RevisionId], [ParentId], [OfficialName], [IsEarth], [IsContinent], [IsCountry], [IsAdmin1], [IsAdmin2], [IsAdmin3], [Latitude], [Longitude], [NorthLatitude], [EastLongitude], [SouthLatitude], [WestLongitude], [EntityId]);


GO
PRINT N'Creating FK_Places.GeoPlanetPlace_Places.Place_PlaceId...';


GO
ALTER TABLE [Places].[GeoPlanetPlace] WITH NOCHECK
    ADD CONSTRAINT [FK_Places.GeoPlanetPlace_Places.Place_PlaceId] FOREIGN KEY ([PlaceId]) REFERENCES [Places].[Place] ([RevisionId]);


GO
PRINT N'Creating FK_Places.PlaceName_Places.Place_NameForPlaceId...';


GO
ALTER TABLE [Places].[PlaceName] WITH NOCHECK
    ADD CONSTRAINT [FK_Places.PlaceName_Places.Place_NameForPlaceId] FOREIGN KEY ([NameForPlaceId]) REFERENCES [Places].[Place] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Places.PlaceNode_Places.Place_AncestorId...';


GO
ALTER TABLE [Places].[PlaceNode] WITH NOCHECK
    ADD CONSTRAINT [FK_Places.PlaceNode_Places.Place_AncestorId] FOREIGN KEY ([AncestorId]) REFERENCES [Places].[Place] ([RevisionId]);


GO
PRINT N'Creating FK_Places.PlaceNode_Places.Place_OffspringId...';


GO
ALTER TABLE [Places].[PlaceNode] WITH NOCHECK
    ADD CONSTRAINT [FK_Places.PlaceNode_Places.Place_OffspringId] FOREIGN KEY ([OffspringId]) REFERENCES [Places].[Place] ([RevisionId]);


GO
PRINT N'Creating FK_Places.Place_Places.Place_ParentId...';


GO
ALTER TABLE [Places].[Place] WITH NOCHECK
    ADD CONSTRAINT [FK_Places.Place_Places.Place_ParentId] FOREIGN KEY ([ParentId]) REFERENCES [Places].[Place] ([RevisionId]);


GO
PRINT N'Creating FK_ActivitiesV2.ActivityLocation_Places.Place_PlaceId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityLocation] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityLocation_Places.Place_PlaceId] FOREIGN KEY ([PlaceId]) REFERENCES [Places].[Place] ([RevisionId]);


GO
PRINT N'Creating FK_Establishments.EstablishmentLocationInPlace_Places.Place_PlaceId...';


GO
ALTER TABLE [Establishments].[EstablishmentLocationInPlace] WITH NOCHECK
    ADD CONSTRAINT [FK_Establishments.EstablishmentLocationInPlace_Places.Place_PlaceId] FOREIGN KEY ([PlaceId]) REFERENCES [Places].[Place] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Places.GeoNamesToponym_Places.Place_PlaceId...';


GO
ALTER TABLE [Places].[GeoNamesToponym] WITH NOCHECK
    ADD CONSTRAINT [FK_Places.GeoNamesToponym_Places.Place_PlaceId] FOREIGN KEY ([PlaceId]) REFERENCES [Places].[Place] ([RevisionId]);


GO
PRINT N'Creating FK_People.Person_Files.ExternalFile_PhotoId...';


GO
ALTER TABLE [People].[Person] WITH NOCHECK
    ADD CONSTRAINT [FK_People.Person_Files.ExternalFile_PhotoId] FOREIGN KEY ([PhotoId]) REFERENCES [Files].[ExternalFile] ([Id]);


GO
PRINT N'Creating FK_Representatives.ApplicationRecipient_Representatives.RepModuleSettings_OwnerId...';


GO
ALTER TABLE [Representatives].[ApplicationRecipient] WITH NOCHECK
    ADD CONSTRAINT [FK_Representatives.ApplicationRecipient_Representatives.RepModuleSettings_OwnerId] FOREIGN KEY ([OwnerId]) REFERENCES [Representatives].[RepModuleSettings] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO

ALTER TABLE [Places].[GeoPlanetPlace] WITH CHECK CHECK CONSTRAINT [FK_Places.GeoPlanetPlace_Places.Place_PlaceId];

ALTER TABLE [Places].[PlaceName] WITH CHECK CHECK CONSTRAINT [FK_Places.PlaceName_Places.Place_NameForPlaceId];

ALTER TABLE [Places].[PlaceNode] WITH CHECK CHECK CONSTRAINT [FK_Places.PlaceNode_Places.Place_AncestorId];

ALTER TABLE [Places].[PlaceNode] WITH CHECK CHECK CONSTRAINT [FK_Places.PlaceNode_Places.Place_OffspringId];

ALTER TABLE [Places].[Place] WITH CHECK CHECK CONSTRAINT [FK_Places.Place_Places.Place_ParentId];

ALTER TABLE [ActivitiesV2].[ActivityLocation] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityLocation_Places.Place_PlaceId];

ALTER TABLE [Establishments].[EstablishmentLocationInPlace] WITH CHECK CHECK CONSTRAINT [FK_Establishments.EstablishmentLocationInPlace_Places.Place_PlaceId];

ALTER TABLE [Places].[GeoNamesToponym] WITH CHECK CHECK CONSTRAINT [FK_Places.GeoNamesToponym_Places.Place_PlaceId];

ALTER TABLE [People].[Person] WITH CHECK CHECK CONSTRAINT [FK_People.Person_Files.ExternalFile_PhotoId];

ALTER TABLE [Representatives].[ApplicationRecipient] WITH CHECK CHECK CONSTRAINT [FK_Representatives.ApplicationRecipient_Representatives.RepModuleSettings_OwnerId];


GO
PRINT N'Update complete.';


GO
