/*
Deployment script for UCosmicTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
--:setvar DatabaseName "UCosmicTest"
--:setvar DefaultFilePrefix "UCosmicTest"
--:setvar DefaultDataPath "c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"
--:setvar DefaultLogPath "c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"

--GO
--:on error exit
--GO
--/*
--Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
--To re-enable the script after enabling SQLCMD mode, execute the following:
--SET NOEXEC OFF; 
--*/
--:setvar __IsSqlCmdEnabled "True"
--GO
--IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
--    BEGIN
--        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
--        SET NOEXEC ON;
--    END


--GO
USE [UCosmicTest];


GO
/*
The column [ActivitiesV2].[ActivityTag].[ActivityId] is being dropped, data loss could occur.

The column [ActivitiesV2].[ActivityTag].[ActivityValuesId] on table [ActivitiesV2].[ActivityTag] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

IF EXISTS (select top 1 1 from [ActivitiesV2].[ActivityTag])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The table [ActivitiesV2].[ActivityType] is being dropped and re-created since all non-computed columns within the table have been redefined.
*/

IF EXISTS (select top 1 1 from [ActivitiesV2].[ActivityType])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
/*
The column [ActivitiesV2].[ActivityValues].[TypeId] is being dropped, data loss could occur.
*/

IF EXISTS (select top 1 1 from [ActivitiesV2].[ActivityValues])
    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

GO
PRINT N'Dropping FK_ActivitiesV2.ActivityTag_ActivitiesV2.Activity_ActivityId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityTag] DROP CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.Activity_ActivityId];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityType] DROP CONSTRAINT [FK_ActivitiesV2.ActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];


GO
PRINT N'Dropping FK_ActivitiesV2.ActivityValues_ActivitiesV2.ActivityType_TypeId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityValues] DROP CONSTRAINT [FK_ActivitiesV2.ActivityValues_ActivitiesV2.ActivityType_TypeId];


GO
PRINT N'Dropping [ActivitiesV2].[ActivityType]...';


GO
DROP TABLE [ActivitiesV2].[ActivityType];


GO
PRINT N'Starting rebuilding table [ActivitiesV2].[ActivityTag]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [ActivitiesV2].[tmp_ms_xx_ActivityTag] (
    [RevisionId]         INT              IDENTITY (1, 1) NOT NULL,
    [ActivityValuesId]   INT              NOT NULL,
    [Number]             INT              NOT NULL,
    [Text]               NVARCHAR (500)   NOT NULL,
    [DomainType]         NVARCHAR (20)    NOT NULL,
    [DomainKey]          INT              NULL,
    [Mode]               NVARCHAR (20)    NOT NULL,
    [EntityId]           UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]       DATETIME         NOT NULL,
    [CreatedByPrincipal] NVARCHAR (256)   NULL,
    [UpdatedOnUtc]       DATETIME         NULL,
    [UpdatedByPrincipal] NVARCHAR (256)   NULL,
    [Version]            ROWVERSION       NOT NULL,
    [IsCurrent]          BIT              NOT NULL,
    [IsArchived]         BIT              NOT NULL,
    [IsDeleted]          BIT              NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_ActivitiesV2.ActivityTag] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [ActivitiesV2].[ActivityTag])
    BEGIN
        SET IDENTITY_INSERT [ActivitiesV2].[tmp_ms_xx_ActivityTag] ON;
        INSERT INTO [ActivitiesV2].[tmp_ms_xx_ActivityTag] ([RevisionId], [Number], [Text], [DomainType], [DomainKey], [Mode], [EntityId], [CreatedOnUtc], [CreatedByPrincipal], [UpdatedOnUtc], [UpdatedByPrincipal], [IsCurrent], [IsArchived], [IsDeleted])
        SELECT   [RevisionId],
                 [Number],
                 [Text],
                 [DomainType],
                 [DomainKey],
                 [Mode],
                 [EntityId],
                 [CreatedOnUtc],
                 [CreatedByPrincipal],
                 [UpdatedOnUtc],
                 [UpdatedByPrincipal],
                 [IsCurrent],
                 [IsArchived],
                 [IsDeleted]
        FROM     [ActivitiesV2].[ActivityTag]
        ORDER BY [RevisionId] ASC;
        SET IDENTITY_INSERT [ActivitiesV2].[tmp_ms_xx_ActivityTag] OFF;
    END

DROP TABLE [ActivitiesV2].[ActivityTag];

EXECUTE sp_rename N'[ActivitiesV2].[tmp_ms_xx_ActivityTag]', N'ActivityTag';

EXECUTE sp_rename N'[ActivitiesV2].[tmp_ms_xx_constraint_PK_ActivitiesV2.ActivityTag]', N'PK_ActivitiesV2.ActivityTag', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [ActivitiesV2].[ActivityTag].[IX_ActivityValuesId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ActivityValuesId]
    ON [ActivitiesV2].[ActivityTag]([ActivityValuesId] ASC);


GO
PRINT N'Creating [ActivitiesV2].[ActivityType]...';


GO
CREATE TABLE [ActivitiesV2].[ActivityType] (
    [RevisionId]         INT              IDENTITY (1, 1) NOT NULL,
    [ActivityValuesId]   INT              NOT NULL,
    [TypeId]             INT              NOT NULL,
    [EntityId]           UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]       DATETIME         NOT NULL,
    [CreatedByPrincipal] NVARCHAR (256)   NULL,
    [UpdatedOnUtc]       DATETIME         NULL,
    [UpdatedByPrincipal] NVARCHAR (256)   NULL,
    [Version]            ROWVERSION       NOT NULL,
    [IsCurrent]          BIT              NOT NULL,
    [IsArchived]         BIT              NOT NULL,
    [IsDeleted]          BIT              NOT NULL,
    CONSTRAINT [PK_ActivitiesV2.ActivityType] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);


GO
PRINT N'Creating [ActivitiesV2].[ActivityType].[IX_TypeId]...';


GO
CREATE NONCLUSTERED INDEX [IX_TypeId]
    ON [ActivitiesV2].[ActivityType]([TypeId] ASC);


GO
PRINT N'Creating [ActivitiesV2].[ActivityType].[IX_ActivityValuesId]...';


GO
CREATE NONCLUSTERED INDEX [IX_ActivityValuesId]
    ON [ActivitiesV2].[ActivityType]([ActivityValuesId] ASC);


GO
PRINT N'Altering [ActivitiesV2].[ActivityValues]...';


GO
ALTER TABLE [ActivitiesV2].[ActivityValues] DROP COLUMN [TypeId];


GO
PRINT N'Altering [Files].[LoadableFile]...';


GO
ALTER TABLE [Files].[LoadableFile]
    ADD [Filename] NVARCHAR (MAX) NULL;


GO
PRINT N'Creating [ActivitiesV2].[ActivityDocument]...';


GO
CREATE TABLE [ActivitiesV2].[ActivityDocument] (
    [RevisionId]         INT              IDENTITY (1, 1) NOT NULL,
    [ActivityValuesId]   INT              NOT NULL,
    [FileId]             INT              NULL,
    [ImageId]            INT              NULL,
    [ProxyImageId]       INT              NULL,
    [Mode]               NVARCHAR (20)    NOT NULL,
    [EntityId]           UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]       DATETIME         NOT NULL,
    [CreatedByPrincipal] NVARCHAR (256)   NULL,
    [UpdatedOnUtc]       DATETIME         NULL,
    [UpdatedByPrincipal] NVARCHAR (256)   NULL,
    [Version]            ROWVERSION       NOT NULL,
    [IsCurrent]          BIT              NOT NULL,
    [IsArchived]         BIT              NOT NULL,
    [IsDeleted]          BIT              NOT NULL,
    CONSTRAINT [PK_ActivitiesV2.ActivityDocument] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);


GO
PRINT N'Creating [Employees].[EmployeeActivityType]...';


GO
CREATE TABLE [Employees].[EmployeeActivityType] (
    [Id]                       INT            IDENTITY (1, 1) NOT NULL,
    [Type]                     NVARCHAR (128) NOT NULL,
    [EmployeeModuleSettingsId] INT            NULL,
    CONSTRAINT [PK_Employees.EmployeeActivityType] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Files].[Image]...';


GO
CREATE TABLE [Files].[Image] (
    [Id]       INT             IDENTITY (1, 1) NOT NULL,
    [SourceId] NVARCHAR (MAX)  NULL,
    [Data]     VARBINARY (MAX) NULL,
    CONSTRAINT [PK_Files.Image] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityTag] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_ActivitiesV2.ActivityType_Employees.EmployeeActivityType_TypeId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityType] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityType_Employees.EmployeeActivityType_TypeId] FOREIGN KEY ([TypeId]) REFERENCES [Employees].[EmployeeActivityType] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityType] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_ActivitiesV2.ActivityDocument_Files.LoadableFile_FileId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityDocument_Files.LoadableFile_FileId] FOREIGN KEY ([FileId]) REFERENCES [Files].[LoadableFile] ([Id]);


GO
PRINT N'Creating FK_ActivitiesV2.ActivityDocument_Files.Image_ImageId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityDocument_Files.Image_ImageId] FOREIGN KEY ([ImageId]) REFERENCES [Files].[Image] ([Id]);


GO
PRINT N'Creating FK_ActivitiesV2.ActivityDocument_Files.Image_ProxyImageId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityDocument_Files.Image_ProxyImageId] FOREIGN KEY ([ProxyImageId]) REFERENCES [Files].[Image] ([Id]);


GO
PRINT N'Creating FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId...';


GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Employees.EmployeeActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeActivityType] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId] FOREIGN KEY ([EmployeeModuleSettingsId]) REFERENCES [Employees].[EmployeeModuleSettings] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
ALTER TABLE [ActivitiesV2].[ActivityTag] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId];

ALTER TABLE [ActivitiesV2].[ActivityType] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityType_Employees.EmployeeActivityType_TypeId];

ALTER TABLE [ActivitiesV2].[ActivityType] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId];

ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityDocument_Files.LoadableFile_FileId];

ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityDocument_Files.Image_ImageId];

ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityDocument_Files.Image_ProxyImageId];

ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId];

ALTER TABLE [Employees].[EmployeeActivityType] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];


GO
PRINT N'Update complete.';


GO
