/*
Deployment script for UCosmicPreview

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/
USE [UCosmicTest]
GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
--:setvar DatabaseName "UCosmicPreview"
--:setvar DefaultFilePrefix "UCosmicPreview"
--:setvar DefaultDataPath "c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"
--:setvar DefaultLogPath "c:\Program Files\Microsoft SQL Server\MSSQL10.SQLEXPRESS\MSSQL\DATA\"

--GO
--:on error exit
--GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
--:setvar __IsSqlCmdEnabled "True"
--GO
--IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
--    BEGIN
--        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
--        SET NOEXEC ON;
--    END


--GO
--USE [$(DatabaseName)];


--GO
/*
The column [Activities].[Activity].[UpdatedByPersonId] on table [Activities].[Activity] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

--IF EXISTS (select top 1 1 from [Activities].[Activity])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
/*
The column [People].[Affiliation].[IsPrimary] on table [People].[Affiliation] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

--IF EXISTS (select top 1 1 from [People].[Affiliation])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
/*
The column [People].[Person].[IsActive] on table [People].[Person] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

--IF EXISTS (select top 1 1 from [People].[Person])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
PRINT N'Dropping Activity_Person...';


GO
ALTER TABLE [Activities].[Activity] DROP CONSTRAINT [Activity_Person];


GO
PRINT N'Dropping Establishment_Affiliates...';


GO
ALTER TABLE [People].[Affiliation] DROP CONSTRAINT [Establishment_Affiliates];


GO
PRINT N'Dropping Person_Affiliations...';


GO
ALTER TABLE [People].[Affiliation] DROP CONSTRAINT [Person_Affiliations];


GO
PRINT N'Creating [Employees]...';


GO
CREATE SCHEMA [Employees]
    AUTHORIZATION [dbo];


GO
PRINT N'Starting rebuilding table [Activities].[Activity]...';


GO
/*
The column [Activities].[Activity].[UpdatedByPersonId] on table [Activities].[Activity] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

--IF EXISTS (select top 1 1 from [Activities].[Activity])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
BEGIN TRANSACTION;

-- drop referencing keys
ALTER TABLE [Activities].[ActivityTag] DROP CONSTRAINT [ActivityTag_Activity]
ALTER TABLE [Activities].[DraftedTag] DROP CONSTRAINT [DraftedTag_Activity]

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [Activities].[tmp_ms_xx_Activity] (
    [PersonId]          INT              NOT NULL,
    [Number]            INT              NOT NULL,
    [EntityId]          UNIQUEIDENTIFIER NOT NULL,
    [Mode]              NVARCHAR (20)    NOT NULL,
    [Title]             NVARCHAR (200)   NULL,
    [Content]           NTEXT            NULL,
    [StartsOn]          DATETIME         NULL,
    [EndsOn]            DATETIME         NULL,
    [CountryId]         INT              NULL,
    [TypeId]            INT              NULL,
    [DraftedTitle]      NVARCHAR (200)   NULL,
    [DraftedContent]    NTEXT            NULL,
    [DraftedStartsOn]   DATETIME         NULL,
    [DraftedEndsOn]     DATETIME         NULL,
    [DraftedCountryId]  INT              NULL,
    [DraftedTypeId]     INT              NULL,
    [CreatedOn]         DATETIME         NOT NULL,
    [UpdatedOn]         DATETIME         NOT NULL,
    [UpdatedByPersonId] INT              NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Activities.Activity] PRIMARY KEY CLUSTERED ([PersonId] ASC, [Number] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [Activities].[Activity])
    BEGIN
        
        INSERT INTO [Activities].[tmp_ms_xx_Activity] ([PersonId], [Number], [EntityId], [Mode], [Title], [Content], [StartsOn], [EndsOn], [DraftedTitle], [DraftedContent], [DraftedStartsOn], [DraftedEndsOn], [CreatedOn], [UpdatedOn], [UpdatedByPersonId])
        SELECT   [PersonId],
                 [Number],
                 [EntityId],
                 [Mode],
                 [Title],
                 [Content],
                 [StartsOn],
                 [EndsOn],
                 [DraftedTitle],
                 [DraftedContent],
                 [DraftedStartsOn],
                 [DraftedEndsOn],
                 [CreatedOn],
                 [UpdatedOn],
				 [PersonId]
        FROM     [Activities].[Activity]
        ORDER BY [Activities].[Activity].[PersonId] ASC, [Number] ASC;
        
    END

DROP TABLE [Activities].[Activity];

EXECUTE sp_rename N'[Activities].[tmp_ms_xx_Activity]', N'Activity';

EXECUTE sp_rename N'[Activities].[tmp_ms_xx_constraint_PK_Activities.Activity]', N'PK_Activities.Activity', N'OBJECT';

--restore referencing keys
ALTER TABLE [Activities].[ActivityTag]  WITH NOCHECK ADD  CONSTRAINT [ActivityTag_Activity] FOREIGN KEY([ActivityPersonId], [ActivityNumber])
REFERENCES [Activities].[Activity] ([PersonId], [Number])
ON DELETE CASCADE
GO
ALTER TABLE [Activities].[ActivityTag] CHECK CONSTRAINT [ActivityTag_Activity]
GO
ALTER TABLE [Activities].[DraftedTag]  WITH NOCHECK ADD  CONSTRAINT [DraftedTag_Activity] FOREIGN KEY([ActivityPersonId], [ActivityNumber])
REFERENCES [Activities].[Activity] ([PersonId], [Number])
ON DELETE CASCADE
GO
ALTER TABLE [Activities].[DraftedTag] CHECK CONSTRAINT [DraftedTag_Activity]
GO

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO


PRINT N'Creating [Activities].[Activity].[IX_PersonId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PersonId]
    ON [Activities].[Activity]([PersonId] ASC);


GO
PRINT N'Creating [Activities].[Activity].[IX_UpdatedByPersonId]...';


GO
CREATE NONCLUSTERED INDEX [IX_UpdatedByPersonId]
    ON [Activities].[Activity]([UpdatedByPersonId] ASC);


GO
/*
The column [People].[Affiliation].[IsPrimary] on table [People].[Affiliation] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

--IF EXISTS (select top 1 1 from [People].[Affiliation])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
PRINT N'Starting rebuilding table [People].[Affiliation]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [People].[tmp_ms_xx_Affiliation] (
    [PersonId]                      INT            NOT NULL,
    [EstablishmentId]               INT            NOT NULL,
    [JobTitles]                     NVARCHAR (500) NULL,
    [IsDefault]                     BIT            NOT NULL,
    [IsPrimary]                     BIT            NOT NULL,
    [IsAcknowledged]                BIT            NOT NULL,
    [IsClaimingStudent]             BIT            NOT NULL,
    [IsClaimingEmployee]            BIT            NOT NULL,
    [IsClaimingInternationalOffice] BIT            NOT NULL,
    [IsClaimingAdministrator]       BIT            NOT NULL,
    [IsClaimingFaculty]             BIT            NOT NULL,
    [IsClaimingStaff]               BIT            NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_People.Affiliation] PRIMARY KEY CLUSTERED ([PersonId] ASC, [EstablishmentId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [People].[Affiliation])
    BEGIN
        
        INSERT INTO [People].[tmp_ms_xx_Affiliation] ([PersonId], [EstablishmentId], [JobTitles], [IsDefault], [IsPrimary], [IsAcknowledged], [IsClaimingStudent], [IsClaimingEmployee], [IsClaimingInternationalOffice], [IsClaimingAdministrator], [IsClaimingFaculty], [IsClaimingStaff])
        SELECT   [PersonId],
                 [EstablishmentId],
                 [JobTitles],
                 [IsDefault],
                 [IsDefault],
                 [IsAcknowledged],
                 [IsClaimingStudent],
                 [IsClaimingEmployee],
                 [IsClaimingInternationalOffice],
                 [IsClaimingAdministrator],
                 [IsClaimingFaculty],
                 [IsClaimingStaff]
        FROM     [People].[Affiliation]
        ORDER BY [PersonId] ASC, [EstablishmentId] ASC;
        
    END

DROP TABLE [People].[Affiliation];

EXECUTE sp_rename N'[People].[tmp_ms_xx_Affiliation]', N'Affiliation';

EXECUTE sp_rename N'[People].[tmp_ms_xx_constraint_PK_People.Affiliation]', N'PK_People.Affiliation', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [People].[Affiliation].[IX_EstablishmentId]...';


GO
CREATE NONCLUSTERED INDEX [IX_EstablishmentId]
    ON [People].[Affiliation]([EstablishmentId] ASC);


GO
PRINT N'Creating [People].[Affiliation].[IX_PersonId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PersonId]
    ON [People].[Affiliation]([PersonId] ASC);


GO
PRINT N'Starting rebuilding table [People].[Person]...';


GO
/*
The column [People].[Person].[IsActive] on table [People].[Person] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/

--IF EXISTS (select top 1 1 from [People].[Person])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT

--GO
BEGIN TRANSACTION;

-- drop referencing keys
ALTER TABLE [Identity].[User] DROP CONSTRAINT [Person_User]
ALTER TABLE [InstitutionalAgreements].[InstitutionalAgreementContact] DROP CONSTRAINT [InstitutionalAgreementContact_Person]
ALTER TABLE [People].[EmailAddress] DROP CONSTRAINT [Person_Emails]
ALTER TABLE [People].[EmailMessage] DROP CONSTRAINT [Person_Messages]


SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [People].[tmp_ms_xx_Person] (
    [RevisionId]           INT              IDENTITY (1, 1) NOT NULL,
    [IsActive]             BIT              NOT NULL,
    [IsDisplayNameDerived] BIT              NOT NULL,
    [DisplayName]          NVARCHAR (200)   NOT NULL,
    [Salutation]           NVARCHAR (50)    NULL,
    [FirstName]            NVARCHAR (100)   NULL,
    [MiddleName]           NVARCHAR (100)   NULL,
    [LastName]             NVARCHAR (100)   NULL,
    [Suffix]               NVARCHAR (50)    NULL,
    [Gender]               CHAR (1)         NULL,
    [EntityId]             UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]         DATETIME         NOT NULL,
    [CreatedByPrincipal]   NVARCHAR (256)   NULL,
    [UpdatedOnUtc]         DATETIME         NULL,
    [UpdatedByPrincipal]   NVARCHAR (256)   NULL,
    [Version]              ROWVERSION       NOT NULL,
    [IsCurrent]            BIT              NOT NULL,
    [IsArchived]           BIT              NOT NULL,
    [IsDeleted]            BIT              NOT NULL,
    [PhotoId]              INT              NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_People.Person] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [People].[Person])
    BEGIN
        SET IDENTITY_INSERT [People].[tmp_ms_xx_Person] ON;
        INSERT INTO [People].[tmp_ms_xx_Person] ([RevisionId], [IsActive], [IsDisplayNameDerived], [DisplayName], [Salutation], [FirstName], [MiddleName], [LastName], [Suffix], [Gender], [EntityId], [CreatedOnUtc], [CreatedByPrincipal], [UpdatedOnUtc], [UpdatedByPrincipal], [IsCurrent], [IsArchived], [IsDeleted])
        SELECT   [RevisionId],
				 1,
                 [IsDisplayNameDerived],
                 [DisplayName],
                 [Salutation],
                 [FirstName],
                 [MiddleName],
                 [LastName],
                 [Suffix],
				 NULL,
                 [EntityId],
                 [CreatedOnUtc],
                 [CreatedByPrincipal],
                 [UpdatedOnUtc],
                 [UpdatedByPrincipal],
                 [IsCurrent],
                 [IsArchived],
                 [IsDeleted]
        FROM     [People].[Person]
        ORDER BY [RevisionId] ASC;
        SET IDENTITY_INSERT [People].[tmp_ms_xx_Person] OFF;
    END

DROP TABLE [People].[Person];

EXECUTE sp_rename N'[People].[tmp_ms_xx_Person]', N'Person';

EXECUTE sp_rename N'[People].[tmp_ms_xx_constraint_PK_People.Person]', N'PK_People.Person', N'OBJECT';

-- restore referencing keys
ALTER TABLE [Identity].[User]  WITH NOCHECK ADD  CONSTRAINT [Person_User] FOREIGN KEY([PersonId])
REFERENCES [People].[Person] ([RevisionId])
GO
ALTER TABLE [Identity].[User] CHECK CONSTRAINT [Person_User]
GO
ALTER TABLE [InstitutionalAgreements].[InstitutionalAgreementContact]  WITH NOCHECK ADD  CONSTRAINT [InstitutionalAgreementContact_Person] FOREIGN KEY([PersonId])
REFERENCES [People].[Person] ([RevisionId])
ON DELETE CASCADE
GO
ALTER TABLE [InstitutionalAgreements].[InstitutionalAgreementContact] CHECK CONSTRAINT [InstitutionalAgreementContact_Person]
GO
ALTER TABLE [People].[EmailAddress]  WITH NOCHECK ADD  CONSTRAINT [Person_Emails] FOREIGN KEY([PersonId])
REFERENCES [People].[Person] ([RevisionId])
ON DELETE CASCADE
GO
ALTER TABLE [People].[EmailAddress] CHECK CONSTRAINT [Person_Emails]
GO
ALTER TABLE [People].[EmailMessage]  WITH NOCHECK ADD  CONSTRAINT [Person_Messages] FOREIGN KEY([ToPersonId])
REFERENCES [People].[Person] ([RevisionId])
ON DELETE CASCADE
GO
ALTER TABLE [People].[EmailMessage] CHECK CONSTRAINT [Person_Messages]
GO

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [People].[Person].[IX_PhotoId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PhotoId]
    ON [People].[Person]([PhotoId] ASC);


GO
PRINT N'Creating [Employees].[EmployeeModuleSettings]...';


GO
CREATE TABLE [Employees].[EmployeeModuleSettings] (
    [Id]                     INT           IDENTITY (1, 1) NOT NULL,
    [NotifyAdminOnUpdate]    BIT           NOT NULL,
    [PersonalInfoAnchorText] NVARCHAR (64) NULL,
    [OfferCountry]           BIT           NOT NULL,
    [OfferActivityType]      BIT           NOT NULL,
    [EstablishmentId]        INT           NOT NULL,
    CONSTRAINT [PK_Employees.EmployeeModuleSettings] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Employees].[EmployeeFacultyRank]...';


GO
CREATE TABLE [Employees].[EmployeeFacultyRank] (
    [Id]                       INT            IDENTITY (1, 1) NOT NULL,
    [Rank]                     NVARCHAR (128) NOT NULL,
    [EmployeeModuleSettingsId] INT            NULL,
    CONSTRAINT [PK_Employees.EmployeeFacultyRank] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Employees].[Employee]...';


GO
CREATE TABLE [Employees].[Employee] (
    [Id]                         INT            IDENTITY (1, 1) NOT NULL,
    [AdministrativeAppointments] NVARCHAR (500) NULL,
    [JobTitles]                  NVARCHAR (500) NULL,
    [PersonId]                   INT            NOT NULL,
    [FacultyRankId]              INT            NULL,
    CONSTRAINT [PK_Employees.Employee] PRIMARY KEY CLUSTERED ([Id] ASC)
);
IF NOT EXISTS (SELECT TOP 1 1 
           FROM   [Employees].[Employee])
    BEGIN
        INSERT INTO [Employees].[Employee] ([PersonId], [JobTitles])
        SELECT   i1.[PersonId],
				 i1.[JobTitles]
        FROM     (SELECT p.[RevisionId] AS [PersonId]
					  ,a.[JobTitles] AS [JobTitles]
					FROM [People].[Person] p
					INNER JOIN [People].[Affiliation] a
					ON p.[RevisionId] = a.[PersonId] AND a.[IsDefault] = 1 AND a.[JobTitles] IS NOT NULL) AS i1
        ORDER BY i1.[PersonId] ASC;
    END


GO
PRINT N'Creating [Employees].[EmployeeModuleSettingsNotifyingAdmins]...';


GO
CREATE TABLE [Employees].[EmployeeModuleSettingsNotifyingAdmins] (
    [EmployeeModuleSettingsId] INT NOT NULL,
    [PersonId]                 INT NOT NULL,
    CONSTRAINT [PK_Employees.EmployeeModuleSettingsNotifyingAdmins] PRIMARY KEY CLUSTERED ([EmployeeModuleSettingsId] ASC, [PersonId] ASC)
);


GO
PRINT N'Creating [Activities].[ActivityType]...';


GO
CREATE TABLE [Activities].[ActivityType] (
    [Id]                       INT            IDENTITY (1, 1) NOT NULL,
    [Type]                     NVARCHAR (128) NOT NULL,
    [EmployeeModuleSettingsId] INT            NULL,
    CONSTRAINT [PK_Activities.ActivityType] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Files].[LoadableFile]...';


GO
CREATE TABLE [Files].[LoadableFile] (
    [Id]       INT            IDENTITY (1, 1) NOT NULL,
    [Length]   INT            NOT NULL,
    [MimeType] NVARCHAR (MAX) NULL,
    [Name]     NVARCHAR (MAX) NULL,
    CONSTRAINT [PK_Files.LoadableFile] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [Files].[LoadableFileBinary]...';


GO
CREATE TABLE [Files].[LoadableFileBinary] (
    [Id]      INT             NOT NULL,
    [Content] VARBINARY (MAX) NULL,
    CONSTRAINT [PK_Files.LoadableFileBinary] PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating FK_Activities.Activity_People.Person_PersonId...';


GO
ALTER TABLE [Activities].[Activity] WITH NOCHECK
    ADD CONSTRAINT [FK_Activities.Activity_People.Person_PersonId] FOREIGN KEY ([PersonId]) REFERENCES [People].[Person] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Activities.Activity_People.Person_UpdatedByPersonId...';


GO
ALTER TABLE [Activities].[Activity] WITH NOCHECK
    ADD CONSTRAINT [FK_Activities.Activity_People.Person_UpdatedByPersonId] FOREIGN KEY ([UpdatedByPersonId]) REFERENCES [People].[Person] ([RevisionId]);


GO
PRINT N'Creating FK_People.Affiliation_Establishments.Establishment_EstablishmentId...';


GO
ALTER TABLE [People].[Affiliation] WITH NOCHECK
    ADD CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_EstablishmentId] FOREIGN KEY ([EstablishmentId]) REFERENCES [Establishments].[Establishment] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_People.Affiliation_People.Person_PersonId...';


GO
ALTER TABLE [People].[Affiliation] WITH NOCHECK
    ADD CONSTRAINT [FK_People.Affiliation_People.Person_PersonId] FOREIGN KEY ([PersonId]) REFERENCES [People].[Person] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_People.Person_Files.LoadableFile_PhotoId...';


GO
ALTER TABLE [People].[Person] WITH NOCHECK
    ADD CONSTRAINT [FK_People.Person_Files.LoadableFile_PhotoId] FOREIGN KEY ([PhotoId]) REFERENCES [Files].[LoadableFile] ([Id]);


GO
PRINT N'Creating FK_Employees.EmployeeModuleSettings_Establishments.Establishment_EstablishmentId...';


GO
ALTER TABLE [Employees].[EmployeeModuleSettings] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeModuleSettings_Establishments.Establishment_EstablishmentId] FOREIGN KEY ([EstablishmentId]) REFERENCES [Establishments].[Establishment] ([RevisionId]);


GO
PRINT N'Creating FK_Employees.EmployeeFacultyRank_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeFacultyRank] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeFacultyRank_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId] FOREIGN KEY ([EmployeeModuleSettingsId]) REFERENCES [Employees].[EmployeeModuleSettings] ([Id]);


GO
PRINT N'Creating FK_Employees.Employee_People.Person_PersonId...';


GO
ALTER TABLE [Employees].[Employee] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.Employee_People.Person_PersonId] FOREIGN KEY ([PersonId]) REFERENCES [People].[Person] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Employees.Employee_Employees.EmployeeFacultyRank_FacultyRankId...';


GO
ALTER TABLE [Employees].[Employee] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.Employee_Employees.EmployeeFacultyRank_FacultyRankId] FOREIGN KEY ([FacultyRankId]) REFERENCES [Employees].[EmployeeFacultyRank] ([Id]);


GO
PRINT N'Creating FK_Employees.EmployeeModuleSettingsNotifyingAdmins_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Employees].[EmployeeModuleSettingsNotifyingAdmins] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeModuleSettingsNotifyingAdmins_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId] FOREIGN KEY ([EmployeeModuleSettingsId]) REFERENCES [Employees].[EmployeeModuleSettings] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Employees.EmployeeModuleSettingsNotifyingAdmins_People.Person_PersonId...';


GO
ALTER TABLE [Employees].[EmployeeModuleSettingsNotifyingAdmins] WITH NOCHECK
    ADD CONSTRAINT [FK_Employees.EmployeeModuleSettingsNotifyingAdmins_People.Person_PersonId] FOREIGN KEY ([PersonId]) REFERENCES [People].[Person] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Activities.ActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId...';


GO
ALTER TABLE [Activities].[ActivityType] WITH NOCHECK
    ADD CONSTRAINT [FK_Activities.ActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId] FOREIGN KEY ([EmployeeModuleSettingsId]) REFERENCES [Employees].[EmployeeModuleSettings] ([Id]);


GO
PRINT N'Creating FK_Files.LoadableFileBinary_Files.LoadableFile_Id...';


GO
ALTER TABLE [Files].[LoadableFileBinary] WITH NOCHECK
    ADD CONSTRAINT [FK_Files.LoadableFileBinary_Files.LoadableFile_Id] FOREIGN KEY ([Id]) REFERENCES [Files].[LoadableFile] ([Id]) ON DELETE CASCADE;


GO
PRINT N'Checking existing data against newly created constraints';


GO
--USE [$(DatabaseName)];


--GO
ALTER TABLE [Activities].[Activity] WITH CHECK CHECK CONSTRAINT [FK_Activities.Activity_People.Person_PersonId];

ALTER TABLE [Activities].[Activity] WITH CHECK CHECK CONSTRAINT [FK_Activities.Activity_People.Person_UpdatedByPersonId];

ALTER TABLE [People].[Affiliation] WITH CHECK CHECK CONSTRAINT [FK_People.Affiliation_Establishments.Establishment_EstablishmentId];

ALTER TABLE [People].[Affiliation] WITH CHECK CHECK CONSTRAINT [FK_People.Affiliation_People.Person_PersonId];

ALTER TABLE [People].[Person] WITH CHECK CHECK CONSTRAINT [FK_People.Person_Files.LoadableFile_PhotoId];

ALTER TABLE [Employees].[EmployeeModuleSettings] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeModuleSettings_Establishments.Establishment_EstablishmentId];

ALTER TABLE [Employees].[EmployeeFacultyRank] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeFacultyRank_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];

ALTER TABLE [Employees].[Employee] WITH CHECK CHECK CONSTRAINT [FK_Employees.Employee_People.Person_PersonId];

ALTER TABLE [Employees].[Employee] WITH CHECK CHECK CONSTRAINT [FK_Employees.Employee_Employees.EmployeeFacultyRank_FacultyRankId];

ALTER TABLE [Employees].[EmployeeModuleSettingsNotifyingAdmins] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeModuleSettingsNotifyingAdmins_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];

ALTER TABLE [Employees].[EmployeeModuleSettingsNotifyingAdmins] WITH CHECK CHECK CONSTRAINT [FK_Employees.EmployeeModuleSettingsNotifyingAdmins_People.Person_PersonId];

ALTER TABLE [Activities].[ActivityType] WITH CHECK CHECK CONSTRAINT [FK_Activities.ActivityType_Employees.EmployeeModuleSettings_EmployeeModuleSettingsId];

ALTER TABLE [Files].[LoadableFileBinary] WITH CHECK CHECK CONSTRAINT [FK_Files.LoadableFileBinary_Files.LoadableFile_Id];


GO
PRINT N'Update complete.';


GO
