/*
Deployment script for UCosmicTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
PRINT N'Dropping FK_Identity.User_People.Person_PersonId...';


GO
ALTER TABLE [Identity].[User] DROP CONSTRAINT [FK_Identity.User_People.Person_PersonId];


GO
PRINT N'Dropping FK_Identity.EduPersonScopedAffiliation_Identity.User_UserId...';


GO
ALTER TABLE [Identity].[EduPersonScopedAffiliation] DROP CONSTRAINT [FK_Identity.EduPersonScopedAffiliation_Identity.User_UserId];


GO
PRINT N'Dropping FK_Identity.Preference_Identity.User_UserId...';


GO
ALTER TABLE [Identity].[Preference] DROP CONSTRAINT [FK_Identity.Preference_Identity.User_UserId];


GO
PRINT N'Dropping FK_Identity.RoleGrant_Identity.User_UserId...';


GO
ALTER TABLE [Identity].[RoleGrant] DROP CONSTRAINT [FK_Identity.RoleGrant_Identity.User_UserId];


GO
PRINT N'Dropping FK_Identity.SubjectNameIdentifier_Identity.User_UserId...';


GO
ALTER TABLE [Identity].[SubjectNameIdentifier] DROP CONSTRAINT [FK_Identity.SubjectNameIdentifier_Identity.User_UserId];


GO
PRINT N'Starting rebuilding table [Identity].[User]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [Identity].[tmp_ms_xx_User] (
    [RevisionId]          INT              IDENTITY (1, 1) NOT NULL,
    [TenantId]            INT              NULL,
    [Name]                NVARCHAR (256)   NOT NULL,
    [IsRegistered]        BIT              NOT NULL,
    [EduPersonTargetedId] NVARCHAR (MAX)   NULL,
    [EntityId]            UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]        DATETIME         NOT NULL,
    [CreatedByPrincipal]  NVARCHAR (256)   NULL,
    [UpdatedOnUtc]        DATETIME         NULL,
    [UpdatedByPrincipal]  NVARCHAR (256)   NULL,
    [Version]             ROWVERSION       NOT NULL,
    [IsCurrent]           BIT              NOT NULL,
    [IsArchived]          BIT              NOT NULL,
    [IsDeleted]           BIT              NOT NULL,
    [PersonId]            INT              NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_Identity.User] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [Identity].[User])
    BEGIN
        SET IDENTITY_INSERT [Identity].[tmp_ms_xx_User] ON;
        INSERT INTO [Identity].[tmp_ms_xx_User] ([RevisionId], [Name], [IsRegistered], [EduPersonTargetedId], [EntityId], [CreatedOnUtc], [CreatedByPrincipal], [UpdatedOnUtc], [UpdatedByPrincipal], [IsCurrent], [IsArchived], [IsDeleted], [PersonId])
        SELECT   [RevisionId],
                 [Name],
                 [IsRegistered],
                 [EduPersonTargetedId],
                 [EntityId],
                 [CreatedOnUtc],
                 [CreatedByPrincipal],
                 [UpdatedOnUtc],
                 [UpdatedByPrincipal],
                 [IsCurrent],
                 [IsArchived],
                 [IsDeleted],
                 [PersonId]
        FROM     [Identity].[User]
        ORDER BY [RevisionId] ASC;
        SET IDENTITY_INSERT [Identity].[tmp_ms_xx_User] OFF;
    END

DROP TABLE [Identity].[User];

EXECUTE sp_rename N'[Identity].[tmp_ms_xx_User]', N'User';

EXECUTE sp_rename N'[Identity].[tmp_ms_xx_constraint_PK_Identity.User]', N'PK_Identity.User', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating [Identity].[User].[IX_TenantId]...';


GO
CREATE NONCLUSTERED INDEX [IX_TenantId]
    ON [Identity].[User]([TenantId] ASC);


GO
PRINT N'Creating [Identity].[User].[IX_PersonId]...';


GO
CREATE NONCLUSTERED INDEX [IX_PersonId]
    ON [Identity].[User]([PersonId] ASC);


GO
PRINT N'Creating FK_Identity.User_People.Person_PersonId...';


GO
ALTER TABLE [Identity].[User] WITH NOCHECK
    ADD CONSTRAINT [FK_Identity.User_People.Person_PersonId] FOREIGN KEY ([PersonId]) REFERENCES [People].[Person] ([RevisionId]);


GO
PRINT N'Creating FK_Identity.EduPersonScopedAffiliation_Identity.User_UserId...';


GO
ALTER TABLE [Identity].[EduPersonScopedAffiliation] WITH NOCHECK
    ADD CONSTRAINT [FK_Identity.EduPersonScopedAffiliation_Identity.User_UserId] FOREIGN KEY ([UserId]) REFERENCES [Identity].[User] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Identity.Preference_Identity.User_UserId...';


GO
ALTER TABLE [Identity].[Preference] WITH NOCHECK
    ADD CONSTRAINT [FK_Identity.Preference_Identity.User_UserId] FOREIGN KEY ([UserId]) REFERENCES [Identity].[User] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Identity.RoleGrant_Identity.User_UserId...';


GO
ALTER TABLE [Identity].[RoleGrant] WITH NOCHECK
    ADD CONSTRAINT [FK_Identity.RoleGrant_Identity.User_UserId] FOREIGN KEY ([UserId]) REFERENCES [Identity].[User] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Identity.SubjectNameIdentifier_Identity.User_UserId...';


GO
ALTER TABLE [Identity].[SubjectNameIdentifier] WITH NOCHECK
    ADD CONSTRAINT [FK_Identity.SubjectNameIdentifier_Identity.User_UserId] FOREIGN KEY ([UserId]) REFERENCES [Identity].[User] ([RevisionId]) ON DELETE CASCADE;


GO
PRINT N'Creating FK_Identity.User_Establishments.Establishment_TenantId...';


GO
ALTER TABLE [Identity].[User] WITH NOCHECK
    ADD CONSTRAINT [FK_Identity.User_Establishments.Establishment_TenantId] FOREIGN KEY ([TenantId]) REFERENCES [Establishments].[Establishment] ([RevisionId]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
ALTER TABLE [Identity].[User] WITH CHECK CHECK CONSTRAINT [FK_Identity.User_People.Person_PersonId];

ALTER TABLE [Identity].[EduPersonScopedAffiliation] WITH CHECK CHECK CONSTRAINT [FK_Identity.EduPersonScopedAffiliation_Identity.User_UserId];

ALTER TABLE [Identity].[Preference] WITH CHECK CHECK CONSTRAINT [FK_Identity.Preference_Identity.User_UserId];

ALTER TABLE [Identity].[RoleGrant] WITH CHECK CHECK CONSTRAINT [FK_Identity.RoleGrant_Identity.User_UserId];

ALTER TABLE [Identity].[SubjectNameIdentifier] WITH CHECK CHECK CONSTRAINT [FK_Identity.SubjectNameIdentifier_Identity.User_UserId];

ALTER TABLE [Identity].[User] WITH CHECK CHECK CONSTRAINT [FK_Identity.User_Establishments.Establishment_TenantId];


GO
PRINT N'Update complete.';


GO
