/*
Deployment script for UCosmicTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO



--------------------------------------------------------------------------------------------------------------
----- DROP CONSTRAINTS
--------------------------------------------------------------------------------------------------------------
PRINT N'Dropping DF_ActivityDocument_Visible...';
GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] DROP CONSTRAINT [DF_ActivityDocument_Visible];
GO

PRINT N'Dropping FK_ActivitiesV2.Activity_People.Person_PersonId...';
GO
ALTER TABLE [ActivitiesV2].[Activity] DROP CONSTRAINT [FK_ActivitiesV2.Activity_People.Person_PersonId];
GO

PRINT N'Dropping FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityValues] DROP CONSTRAINT [FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId];
GO

PRINT N'Dropping FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] DROP CONSTRAINT [FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId];
GO

PRINT N'Dropping FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityLocation] DROP CONSTRAINT [FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId];
GO

PRINT N'Dropping FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityTag] DROP CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId];
GO

PRINT N'Dropping FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityType] DROP CONSTRAINT [FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId];
GO

PRINT N'Dropping FK_Files.LoadableFileBinary_Files.LoadableFile_Id...';
GO
ALTER TABLE [Files].[LoadableFileBinary] DROP CONSTRAINT [FK_Files.LoadableFileBinary_Files.LoadableFile_Id];
GO



--------------------------------------------------------------------------------------------------------------
----- DROP old Files tables
--------------------------------------------------------------------------------------------------------------
/*
Table [Files].[Image] is being dropped.  Deployment will halt if the table contains data.
*/
--IF EXISTS (select top 1 1 from [Files].[Image])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT
--GO
PRINT N'Dropping [Files].[Image]...';
GO
DROP TABLE [Files].[Image];
GO

/*
Table [Files].[LoadableFile] is being dropped.  Deployment will halt if the table contains data.
*/
--IF EXISTS (select top 1 1 from [Files].[LoadableFile])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT
--GO
PRINT N'Dropping [Files].[LoadableFile]...';
GO
DROP TABLE [Files].[LoadableFile];
GO

/*
Table [Files].[LoadableFileBinary] is being dropped.  Deployment will halt if the table contains data.
*/
--IF EXISTS (select top 1 1 from [Files].[LoadableFileBinary])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT
--GO
PRINT N'Dropping [Files].[LoadableFileBinary]...';
GO
DROP TABLE [Files].[LoadableFileBinary];
GO

/*
Table [Files].[ProxyImageMimeTypeXRef] is being dropped.  Deployment will halt if the table contains data.
*/
--IF EXISTS (select top 1 1 from [Files].[ProxyImageMimeTypeXRef])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT
--GO
PRINT N'Dropping [Files].[ProxyImageMimeTypeXRef]...';
GO
DROP TABLE [Files].[ProxyImageMimeTypeXRef];
GO



--------------------------------------------------------------------------------------------------------------
----- REBUILD Activity
--------------------------------------------------------------------------------------------------------------
/*
The column [ActivitiesV2].[Activity].[Number] is being dropped, data loss could occur.

The type for column Mode in table [ActivitiesV2].[Activity] is currently  NVARCHAR (20) NOT NULL but is being changed to  VARCHAR (20) NOT NULL. Data loss could occur.
*/
--IF EXISTS (select top 1 1 from [ActivitiesV2].[Activity])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT
--GO
PRINT N'Starting rebuilding table [ActivitiesV2].[Activity]...';
GO
BEGIN TRANSACTION;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET XACT_ABORT ON;

-- delete all activities with orphaned editsourceid
PRINT N'Deleting orphaned activities...';
GO
DELETE
FROM [ActivitiesV2].[Activity]
WHERE [EditSourceId] IS NOT NULL AND [EditSourceId] NOT IN (SELECT [RevisionId] FROM [ActivitiesV2].[Activity])

PRINT N'Deleting orphaned activity values...';
GO
DELETE
FROM [ActivitiesV2].[ActivityValues]
WHERE [ActivityId] NOT IN (SELECT [RevisionId] FROM [ActivitiesV2].[Activity])

PRINT N'Deleting orphaned activity collections...';
GO
DELETE
FROM [ActivitiesV2].[ActivityDocument]
WHERE [ActivityValuesId] NOT IN (SELECT [RevisionId] FROM [ActivitiesV2].[ActivityValues])

DELETE
FROM [ActivitiesV2].[ActivityLocation]
WHERE [ActivityValuesId] NOT IN (SELECT [RevisionId] FROM [ActivitiesV2].[ActivityValues])

DELETE
FROM [ActivitiesV2].[ActivityTag]
WHERE [ActivityValuesId] NOT IN (SELECT [RevisionId] FROM [ActivitiesV2].[ActivityValues])

DELETE
FROM [ActivitiesV2].[ActivityType]
WHERE [ActivityValuesId] NOT IN (SELECT [RevisionId] FROM [ActivitiesV2].[ActivityValues])

CREATE TABLE [ActivitiesV2].[tmp_ms_xx_Activity] (
    [RevisionId]         INT              IDENTITY (1, 1) NOT NULL,
    [PersonId]           INT              NOT NULL,
    [Mode]               VARCHAR (20)     NOT NULL,
    [EntityId]           UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]       DATETIME         NOT NULL,
    [CreatedByPrincipal] NVARCHAR (256)   NULL,
    [UpdatedOnUtc]       DATETIME         NULL,
    [UpdatedByPrincipal] NVARCHAR (256)   NULL,
    [Version]            ROWVERSION       NOT NULL,
    [IsCurrent]          BIT              NOT NULL,
    [IsArchived]         BIT              NOT NULL,
    [IsDeleted]          BIT              NOT NULL,
    [EditSourceId]       INT              NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_ActivitiesV2.Activity] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);

IF EXISTS (SELECT TOP 1 1
           FROM   [ActivitiesV2].[Activity])
    BEGIN
		PRINT N'Rebuilding into new table...';
        SET IDENTITY_INSERT [ActivitiesV2].[tmp_ms_xx_Activity] ON;
        INSERT INTO [ActivitiesV2].[tmp_ms_xx_Activity] ([RevisionId], [PersonId], [Mode], [EditSourceId], [EntityId], [CreatedOnUtc], [CreatedByPrincipal], [UpdatedOnUtc], [UpdatedByPrincipal], [IsCurrent], [IsArchived], [IsDeleted])
        SELECT   a.[RevisionId],
                 a.[PersonId],
                 a.[Mode],
                 a.[EditSourceId],
                 a.[EntityId],
                 a.[CreatedOnUtc],
                 a.[CreatedByPrincipal],
                 a.[UpdatedOnUtc],
                 a.[UpdatedByPrincipal],
                 a.[IsCurrent],
                 a.[IsArchived],
                 a.[IsDeleted]
        FROM     [ActivitiesV2].[Activity] a
        ORDER BY a.[RevisionId] ASC;
        SET IDENTITY_INSERT [ActivitiesV2].[tmp_ms_xx_Activity] OFF;
    END

DROP TABLE [ActivitiesV2].[Activity];

EXECUTE sp_rename N'[ActivitiesV2].[tmp_ms_xx_Activity]', N'Activity';
EXECUTE sp_rename N'[ActivitiesV2].[tmp_ms_xx_constraint_PK_ActivitiesV2.Activity]', N'PK_ActivitiesV2.Activity', N'OBJECT';

COMMIT TRANSACTION;
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;
GO

PRINT N'Creating [ActivitiesV2].[Activity].[IX_PersonId]...';
GO
CREATE NONCLUSTERED INDEX [IX_PersonId]
    ON [ActivitiesV2].[Activity]([PersonId] ASC);
GO

PRINT N'Creating [ActivitiesV2].[Activity].[IX_EditSourceId]...';
GO
CREATE NONCLUSTERED INDEX [IX_EditSourceId]
    ON [ActivitiesV2].[Activity]([EditSourceId] ASC);
GO



--------------------------------------------------------------------------------------------------------------
----- REBUILD ActivityValues
--------------------------------------------------------------------------------------------------------------
PRINT N'Starting rebuilding table [ActivitiesV2].[ActivityValues]...';
GO
BEGIN TRANSACTION;
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;
SET XACT_ABORT ON;

CREATE TABLE [ActivitiesV2].[tmp_ms_xx_ActivityValues] (
    [RevisionId]          INT              IDENTITY (1, 1) NOT NULL,
    [ActivityId]          INT              NOT NULL,
    [Title]               NVARCHAR (500)   NULL,
    [Content]             NTEXT            NULL,
    [StartsOn]            DATETIME         NULL,
    [EndsOn]              DATETIME         NULL,
    [OnGoing]             BIT              NULL,
    [StartsFormat]        VARCHAR (10)     NULL,
    [EndsFormat]          VARCHAR (10)     NULL,
    [Mode]                NVARCHAR (20)    NOT NULL,
    [WasExternallyFunded] BIT              NULL,
    [WasInternallyFunded] BIT              NULL,
    [EntityId]            UNIQUEIDENTIFIER NOT NULL,
    [CreatedOnUtc]        DATETIME         NOT NULL,
    [CreatedByPrincipal]  NVARCHAR (256)   NULL,
    [UpdatedOnUtc]        DATETIME         NULL,
    [UpdatedByPrincipal]  NVARCHAR (256)   NULL,
    [Version]             ROWVERSION       NOT NULL,
    [IsCurrent]           BIT              NOT NULL,
    [IsArchived]          BIT              NOT NULL,
    [IsDeleted]           BIT              NOT NULL,
    CONSTRAINT [tmp_ms_xx_constraint_PK_ActivitiesV2.ActivityValues] PRIMARY KEY CLUSTERED ([RevisionId] ASC)
);

IF EXISTS (SELECT TOP 1 1
           FROM   [ActivitiesV2].[ActivityValues])
    BEGIN
        SET IDENTITY_INSERT [ActivitiesV2].[tmp_ms_xx_ActivityValues] ON;
        INSERT INTO [ActivitiesV2].[tmp_ms_xx_ActivityValues] ([RevisionId], [ActivityId], [Title], [Content], [StartsOn], [EndsOn], [StartsFormat], [EndsFormat], [OnGoing], [Mode], [WasExternallyFunded], [WasInternallyFunded], [EntityId], [CreatedOnUtc], [CreatedByPrincipal], [UpdatedOnUtc], [UpdatedByPrincipal], [IsCurrent], [IsArchived], [IsDeleted])
        SELECT   [RevisionId],
                 [ActivityId],
                 [Title],
                 [Content],
                 [StartsOn],
                 [EndsOn],
                 [DateFormat],
                 [DateFormat],
                 [OnGoing],
                 [Mode],
                 [WasExternallyFunded],
                 [WasInternallyFunded],
                 [EntityId],
                 [CreatedOnUtc],
                 [CreatedByPrincipal],
                 [UpdatedOnUtc],
                 [UpdatedByPrincipal],
                 [IsCurrent],
                 [IsArchived],
                 [IsDeleted]
        FROM     [ActivitiesV2].[ActivityValues]
        ORDER BY [RevisionId] ASC;
        SET IDENTITY_INSERT [ActivitiesV2].[tmp_ms_xx_ActivityValues] OFF;
    END

DROP TABLE [ActivitiesV2].[ActivityValues];

EXECUTE sp_rename N'[ActivitiesV2].[tmp_ms_xx_ActivityValues]', N'ActivityValues';
EXECUTE sp_rename N'[ActivitiesV2].[tmp_ms_xx_constraint_PK_ActivitiesV2.ActivityValues]', N'PK_ActivitiesV2.ActivityValues', N'OBJECT';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO

PRINT N'Creating [ActivitiesV2].[ActivityValues].[IX_ActivityId]...';
GO
CREATE NONCLUSTERED INDEX [IX_ActivityId]
    ON [ActivitiesV2].[ActivityValues]([ActivityId] ASC);
GO



--------------------------------------------------------------------------------------------------------------
----- ALTER ActivityDocument DROP COLUMNS & change [Length] to NOT NULL
--------------------------------------------------------------------------------------------------------------
/*
The column [ActivitiesV2].[ActivityDocument].[FileId] is being dropped, data loss could occur.

The column [ActivitiesV2].[ActivityDocument].[ImageId] is being dropped, data loss could occur.

The column [ActivitiesV2].[ActivityDocument].[Visible] is being dropped, data loss could occur.

The column Length on table [ActivitiesV2].[ActivityDocument] must be changed from NULL to NOT NULL. If the table contains data, the ALTER script may not work. To avoid this issue, you must add values to this column for all rows or mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
*/
--IF EXISTS (select top 1 1 from [ActivitiesV2].[ActivityDocument])
--    RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127) WITH NOWAIT
--GO
PRINT N'Altering [ActivitiesV2].[ActivityDocument]...';
GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] DROP COLUMN [FileId], COLUMN [ImageId], COLUMN [Visible], COLUMN [Mode];
GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] ALTER COLUMN [Length] INT NOT NULL;
GO



--------------------------------------------------------------------------------------------------------------
----- ALTER ActivityTag DROP COLUMNS
--------------------------------------------------------------------------------------------------------------
PRINT N'Altering [ActivitiesV2].[ActivityTag]...';
GO
ALTER TABLE [ActivitiesV2].[ActivityTag] DROP COLUMN [Number], COLUMN [Mode]
GO



--------------------------------------------------------------------------------------------------------------
----- CREATE CONSTRAINTS
--------------------------------------------------------------------------------------------------------------

PRINT N'Creating FK_ActivitiesV2.Activity_People.Person_PersonId...';
GO

ALTER TABLE [ActivitiesV2].[Activity] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.Activity_People.Person_PersonId] FOREIGN KEY ([PersonId]) REFERENCES [People].[Person] ([RevisionId]);
GO

PRINT N'Creating FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId...';
GO

ALTER TABLE [ActivitiesV2].[ActivityValues] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId] FOREIGN KEY ([ActivityId]) REFERENCES [ActivitiesV2].[Activity] ([RevisionId]) ON DELETE CASCADE;
GO

PRINT N'Creating FK_ActivitiesV2.Activity_ActivitiesV2.Activity_EditSourceId...';
GO
ALTER TABLE [ActivitiesV2].[Activity] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.Activity_ActivitiesV2.Activity_EditSourceId] FOREIGN KEY ([EditSourceId]) REFERENCES [ActivitiesV2].[Activity] ([RevisionId]);
GO

PRINT N'Creating FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;
GO

PRINT N'Creating FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityLocation] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;
GO

PRINT N'Creating FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityTag] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;
GO

PRINT N'Creating FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId...';
GO
ALTER TABLE [ActivitiesV2].[ActivityType] WITH NOCHECK
    ADD CONSTRAINT [FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId] FOREIGN KEY ([ActivityValuesId]) REFERENCES [ActivitiesV2].[ActivityValues] ([RevisionId]) ON DELETE CASCADE;
GO



--------------------------------------------------------------------------------------------------------------
----- CHECK CONSTRAINTS
--------------------------------------------------------------------------------------------------------------
PRINT N'Checking existing data against newly created constraints';
GO

PRINT N'Checking [FK_ActivitiesV2.Activity_People.Person_PersonId]';
GO
ALTER TABLE [ActivitiesV2].[Activity] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.Activity_People.Person_PersonId];

PRINT N'Checking [FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId]';
GO
ALTER TABLE [ActivitiesV2].[ActivityValues] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityValues_ActivitiesV2.Activity_ActivityId];

PRINT N'Checking [FK_ActivitiesV2.Activity_ActivitiesV2.Activity_EditSourceId]';
GO
ALTER TABLE [ActivitiesV2].[Activity] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.Activity_ActivitiesV2.Activity_EditSourceId];

ALTER TABLE [ActivitiesV2].[ActivityDocument] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityDocument_ActivitiesV2.ActivityValues_ActivityValuesId];
ALTER TABLE [ActivitiesV2].[ActivityLocation] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityLocation_ActivitiesV2.ActivityValues_ActivityValuesId];
ALTER TABLE [ActivitiesV2].[ActivityTag] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityTag_ActivitiesV2.ActivityValues_ActivityValuesId];
ALTER TABLE [ActivitiesV2].[ActivityType] WITH CHECK CHECK CONSTRAINT [FK_ActivitiesV2.ActivityType_ActivitiesV2.ActivityValues_ActivityValuesId];


GO

PRINT N'Update complete.';
GO
