// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UCosmic.Web.Mvc.Controllers
{
    public partial class ActivitiesController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ActivitiesController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Edit()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult ActivitiesSpike()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActivitiesSpike);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActivitiesController Actions { get { return MVC.Activities; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "Activities";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "Activities";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Get = "Get";
            public readonly string Create = "Create";
            public readonly string Edit = "Edit";
            public readonly string ActivitiesSpike = "ActivitiesSpike";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Get = "Get";
            public const string Create = "Create";
            public const string Edit = "Edit";
            public const string ActivitiesSpike = "ActivitiesSpike";
        }


        static readonly ActionParamsClass_Edit s_params_Edit = new ActionParamsClass_Edit();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Edit EditParams { get { return s_params_Edit; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Edit
        {
            public readonly string activityId = "activityId";
        }
        static readonly ActionParamsClass_ActivitiesSpike s_params_ActivitiesSpike = new ActionParamsClass_ActivitiesSpike();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_ActivitiesSpike ActivitiesSpikeParams { get { return s_params_ActivitiesSpike; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_ActivitiesSpike
        {
            public readonly string activityId = "activityId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _ActivitiesSpikeContent = "_ActivitiesSpikeContent";
                public readonly string _ActivitiesSpikeSide = "_ActivitiesSpikeSide";
                public readonly string _Bib = "_Bib";
                public readonly string _EditStyles = "_EditStyles";
                public readonly string ActivitiesSpike = "ActivitiesSpike";
                public readonly string Edit = "Edit";
            }
            public readonly string _ActivitiesSpikeContent = "~/Views/Activities/_ActivitiesSpikeContent.cshtml";
            public readonly string _ActivitiesSpikeSide = "~/Views/Activities/_ActivitiesSpikeSide.cshtml";
            public readonly string _Bib = "~/Views/Activities/_Bib.cshtml";
            public readonly string _EditStyles = "~/Views/Activities/_EditStyles.cshtml";
            public readonly string ActivitiesSpike = "~/Views/Activities/ActivitiesSpike.cshtml";
            public readonly string Edit = "~/Views/Activities/Edit.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ActivitiesController : UCosmic.Web.Mvc.Controllers.ActivitiesController
    {
        public T4MVC_ActivitiesController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Get()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get);
            return callInfo;
        }

        public override System.Web.Mvc.RedirectToRouteResult Create()
        {
            var callInfo = new T4MVC_System_Web_Mvc_RedirectToRouteResult(Area, Name, ActionNames.Create);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult Edit(int activityId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Edit);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "activityId", activityId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult ActivitiesSpike(int activityId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.ActivitiesSpike);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "activityId", activityId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
