// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UCosmic.Web.Mvc.Areas.ActivitiesDeprecated.Controllers
{
    public partial class ActivitySearchController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected ActivitySearchController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult Get()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.JsonResult AutoCompleteKeyword()
        {
            return new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AutoCompleteKeyword);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActivitySearchController Actions { get { return MVC.ActivitiesDeprecated.ActivitySearch; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "ActivitiesDeprecated";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "ActivitySearch";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "ActivitySearch";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string Get = "Get";
            public readonly string AutoCompleteKeyword = "AutoCompleteKeyword";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string Get = "Get";
            public const string AutoCompleteKeyword = "AutoCompleteKeyword";
        }


        static readonly ActionParamsClass_Get s_params_Get = new ActionParamsClass_Get();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_Get GetParams { get { return s_params_Get; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_Get
        {
            public readonly string establishment = "establishment";
            public readonly string keyword = "keyword";
        }
        static readonly ActionParamsClass_AutoCompleteKeyword s_params_AutoCompleteKeyword = new ActionParamsClass_AutoCompleteKeyword();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_AutoCompleteKeyword AutoCompleteKeywordParams { get { return s_params_AutoCompleteKeyword; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_AutoCompleteKeyword
        {
            public readonly string establishment = "establishment";
            public readonly string term = "term";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
            }
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_ActivitySearchController : UCosmic.Web.Mvc.Areas.ActivitiesDeprecated.Controllers.ActivitySearchController
    {
        public T4MVC_ActivitySearchController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult Get(string establishment, string keyword)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.Get);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "establishment", establishment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "keyword", keyword);
            return callInfo;
        }

        public override System.Web.Mvc.JsonResult AutoCompleteKeyword(string establishment, string term)
        {
            var callInfo = new T4MVC_System_Web_Mvc_JsonResult(Area, Name, ActionNames.AutoCompleteKeyword);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "establishment", establishment);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "term", term);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
