// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591
#region T4MVC

using System;
using System.Diagnostics;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Hosting;
using System.Web.Mvc;
using System.Web.Mvc.Ajax;
using System.Web.Mvc.Html;
using System.Web.Routing;
using T4MVC;
namespace UCosmic.Web.Mvc.Controllers
{
    public partial class MyProfileController
    {
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected MyProfileController(Dummy d) { }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToAction(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoute(callInfo.RouteValueDictionary);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        protected RedirectToRouteResult RedirectToActionPermanent(ActionResult result)
        {
            var callInfo = result.GetT4MVCResult();
            return RedirectToRoutePermanent(callInfo.RouteValueDictionary);
        }

        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditDegree()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDegree);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditGeographicExpertise()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditGeographicExpertise);
        }
        [NonAction]
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public System.Web.Mvc.ActionResult EditLanguageExpertise()
        {
            return new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditLanguageExpertise);
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public MyProfileController Actions { get { return MVC.MyProfile; } }
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Area = "";
        [GeneratedCode("T4MVC", "2.0")]
        public readonly string Name = "MyProfile";
        [GeneratedCode("T4MVC", "2.0")]
        public const string NameConst = "MyProfile";

        static readonly ActionNamesClass s_actions = new ActionNamesClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionNamesClass ActionNames { get { return s_actions; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNamesClass
        {
            public readonly string NewDegree = "NewDegree";
            public readonly string EditDegree = "EditDegree";
            public readonly string NewGeographicExpertise = "NewGeographicExpertise";
            public readonly string EditGeographicExpertise = "EditGeographicExpertise";
            public readonly string NewLanguageExpertise = "NewLanguageExpertise";
            public readonly string EditLanguageExpertise = "EditLanguageExpertise";
        }

        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionNameConstants
        {
            public const string NewDegree = "NewDegree";
            public const string EditDegree = "EditDegree";
            public const string NewGeographicExpertise = "NewGeographicExpertise";
            public const string EditGeographicExpertise = "EditGeographicExpertise";
            public const string NewLanguageExpertise = "NewLanguageExpertise";
            public const string EditLanguageExpertise = "EditLanguageExpertise";
        }


        static readonly ActionParamsClass_EditDegree s_params_EditDegree = new ActionParamsClass_EditDegree();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditDegree EditDegreeParams { get { return s_params_EditDegree; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditDegree
        {
            public readonly string degreeId = "degreeId";
        }
        static readonly ActionParamsClass_EditGeographicExpertise s_params_EditGeographicExpertise = new ActionParamsClass_EditGeographicExpertise();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditGeographicExpertise EditGeographicExpertiseParams { get { return s_params_EditGeographicExpertise; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditGeographicExpertise
        {
            public readonly string expertiseId = "expertiseId";
        }
        static readonly ActionParamsClass_EditLanguageExpertise s_params_EditLanguageExpertise = new ActionParamsClass_EditLanguageExpertise();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ActionParamsClass_EditLanguageExpertise EditLanguageExpertiseParams { get { return s_params_EditLanguageExpertise; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ActionParamsClass_EditLanguageExpertise
        {
            public readonly string expertiseId = "expertiseId";
        }
        static readonly ViewsClass s_views = new ViewsClass();
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public ViewsClass Views { get { return s_views; } }
        [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
        public class ViewsClass
        {
            static readonly _ViewNamesClass s_ViewNames = new _ViewNamesClass();
            public _ViewNamesClass ViewNames { get { return s_ViewNames; } }
            public class _ViewNamesClass
            {
                public readonly string _Activities = "_Activities";
                public readonly string _Degrees = "_Degrees";
                public readonly string _EmailAddresses = "_EmailAddresses";
                public readonly string _GeographicExpertises = "_GeographicExpertises";
                public readonly string _InternationalAffiliations = "_InternationalAffiliations";
                public readonly string _LanguageExpertises = "_LanguageExpertises";
                public readonly string _PersonalInfo = "_PersonalInfo";
                public readonly string DegreeForm = "DegreeForm";
                public readonly string GeographicExpertiseForm = "GeographicExpertiseForm";
                public readonly string Index = "Index";
                public readonly string InternationalAffiliationForm = "InternationalAffiliationForm";
                public readonly string LanguageExpertiseForm = "LanguageExpertiseForm";
            }
            public readonly string _Activities = "~/Views/MyProfile/_Activities.cshtml";
            public readonly string _Degrees = "~/Views/MyProfile/_Degrees.cshtml";
            public readonly string _EmailAddresses = "~/Views/MyProfile/_EmailAddresses.cshtml";
            public readonly string _GeographicExpertises = "~/Views/MyProfile/_GeographicExpertises.cshtml";
            public readonly string _InternationalAffiliations = "~/Views/MyProfile/_InternationalAffiliations.cshtml";
            public readonly string _LanguageExpertises = "~/Views/MyProfile/_LanguageExpertises.cshtml";
            public readonly string _PersonalInfo = "~/Views/MyProfile/_PersonalInfo.cshtml";
            public readonly string DegreeForm = "~/Views/MyProfile/DegreeForm.cshtml";
            public readonly string GeographicExpertiseForm = "~/Views/MyProfile/GeographicExpertiseForm.cshtml";
            public readonly string Index = "~/Views/MyProfile/Index.cshtml";
            public readonly string InternationalAffiliationForm = "~/Views/MyProfile/InternationalAffiliationForm.cshtml";
            public readonly string LanguageExpertiseForm = "~/Views/MyProfile/LanguageExpertiseForm.cshtml";
        }
    }

    [GeneratedCode("T4MVC", "2.0"), DebuggerNonUserCode]
    public class T4MVC_MyProfileController : UCosmic.Web.Mvc.Controllers.MyProfileController
    {
        public T4MVC_MyProfileController() : base(Dummy.Instance) { }

        public override System.Web.Mvc.ActionResult NewDegree()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewDegree);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditDegree(int degreeId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditDegree);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "degreeId", degreeId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult NewGeographicExpertise()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewGeographicExpertise);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditGeographicExpertise(int expertiseId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditGeographicExpertise);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "expertiseId", expertiseId);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult NewLanguageExpertise()
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.NewLanguageExpertise);
            return callInfo;
        }

        public override System.Web.Mvc.ActionResult EditLanguageExpertise(int expertiseId)
        {
            var callInfo = new T4MVC_System_Web_Mvc_ActionResult(Area, Name, ActionNames.EditLanguageExpertise);
            ModelUnbinderHelpers.AddRouteValues(callInfo.RouteValueDictionary, "expertiseId", expertiseId);
            return callInfo;
        }

    }
}

#endregion T4MVC
#pragma warning restore 1591
